### ISSUE TITLE
配置保存，某些软件强制占用快捷键，我删除后重启软件又占用

### ISSUE THREAD

**Issue by snsnsjsn** [BlackINT3/OpenArk#103]
我在内核里面删除了，结果openark关闭，然后打开软件又占用了快捷键
我不得不在打开openark 进入内核模式一个个删除

没有多选一次性删除

没有保存一个配置文件，只要打开 openark就强制执行删除快捷键后的状态？

这样我起码在打开电脑不关机状态下能删除某些软件sb的设置快捷键

**Comment by BlackINT3** [comment]
#35

**Comment by BlackINT3** [comment]
#35
