### ISSUE TITLE
杀不掉腾讯电脑管家进程

### ISSUE THREAD

**Issue by weisiqian** [BlackINT3/OpenArk#104]
杀不掉腾讯电脑管家进程

![image](https://user-images.githubusercontent.com/19994951/206641774-8eb82c6a-077d-4279-bdb7-400f025e61c1.png)

**Comment by SYREB** [comment]
直接右键退出也还存在吗？

**Comment by weisiqian** [comment]
右键->结束进程树，结束进程都没用

**Comment by BlackINT3** [comment]
@weisiqian @SYREB 
v1.3.2 supported. it can terminate anything.
BTW: You need enter kernel mode firstly.

#96
