### ISSUE TITLE
windows 11 版本号 22h2 22621 进不了内核模式

### ISSUE THREAD

**Issue by ken515** [BlackINT3/OpenArk#105]
[OpenArk::onActionCheckUpdate::::operator ()] [INFO] OpenArk is latest. 
[UNONE::ObLoadDriverW] [ERR] NtLoadDriver service:\Registry\Machine\System\CurrentControlSet\Services\OpenArkDrv64 err:c0000603
[Kernel::onClickKernelMode] [ERR] InstallDriver C:\Users\elvyo\AppData\Local\Temp\OpenArkDrv64.sys err 
[UNONE::ObLoadDriverW] [ERR] NtLoadDriver service:\Registry\Machine\System\CurrentControlSet\Services\OpenArkDrv64 err:c0000603
[Kernel::onClickKernelMode] [ERR] InstallDriver C:\Users\elvyo\AppData\Local\Temp\OpenArkDrv64.sys err 
[UNONE::ObLoadDriverW] [ERR] NtLoadDriver service:\Registry\Machine\System\CurrentControlSet\Services\OpenArkDrv64 err:c0000603
[Kernel::onClickKernelMode] [ERR] InstallDriver C:\Users\elvyo\AppData\Local\Temp\OpenArkDrv64.sys err 
[Kernel::ShowSystemNotify] [ERR] NotifyEnumProcess err 
[Kernel::ShowSystemNotify] [ERR] NotifyEnumThread err 
[Kernel::ShowSystemNotify] [ERR] NotifyEnumImage err 
[Kernel::ShowSystemNotify] [ERR] NotifyEnumRegistry err 
[UNONE::ObLoadDriverW] [ERR] NtLoadDriver service:\Registry\Machine\System\CurrentControlSet\Services\OpenArkDrv64 err:c0000603
[Kernel::onClickKernelMode] [ERR] InstallDriver C:\Users\elvyo\AppData\Local\Temp\OpenArkDrv64.sys err

**Comment by ken515** [comment]
Copyright (C) 2019 BlackINT3 https://github.com/BlackINT3/OpenArk
[UNONE::FsReadFileDataW] [WARN] C:\Users\elvyo\AppData\Roaming\OpenArk\console\history.txt is empty file
[unknown:0][WARN]QMetaObject::invokeMethod: No such method QWidget::onRefresh()
[ArkDrvApi::Process::OpenProcess] [ERR] OpenProcess by Kernel pid:4 err:2 
[ArkDrvApi::Process::OpenProcess] [ERR] OpenProcess by Kernel pid:4 err:2 
[OpenArk::onActionCheckUpdate] [INFO] requset server:http://file.blackint3.com:88/openark/version.txt 
[OpenArk::onActionCheckUpdate::::operator ()] [INFO] local appver:1.2.2, build:202201282330 
[OpenArk::onActionCheckUpdate::::operator ()] [INFO] server responsed:{
"err": 0,
"appver": "1.2.2",
"appbd": "202201282330",
"appcl": "5aKe5Yqg6LCD6K+V56ym5Y+36K6+572u44CB5byA5Y+R5LqG5Zu95YaF5Yqg6YCf6ZWc5YOP6IqC54K5Cueoi+W6j+aUr+aMgeWcqOe6v+WNh+e6pwrlt6Xlhbfnm67lvZXmlK/mjIHkv67mlLnjgIHlop7liqDkuIDkupvlt6XlhbcK5pSv5oyB5pWw5o2u5a+85Ye65Yqf6IO977yM5L6L5aaC54Ot6ZSu44CB6amx5Yqo5YiX6KGo562JCuafpeeci+i/m+eoi+aooeWdl+aXtuWPr+i/h+a7pOezu+e7n+aooeWdlwpQReaJq+aPj+WZqOaUr+aMgeS4i+i9veW+rui9r3BkYuespuWPt+aWh+S7tgrmlK/mjIHmi5bmi73mlofku7bmn6XnnIvmlofku7bljaDnlKgK5paw5bm05b+r5LmQIDIwMjLvvIEKLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tCkFkZCBkZWJ1ZyBzeXN0ZW0gYW5kIGNuLW1pcnJvciByZXBvIGZlYXR1cmVzLgpBZGQgb25saW5lIHVwZ3JhZGUgZmVhdHVyZS4KQWRkIGNoYW5nZSByZXZlcnNlIHRvb2wgZm9sZGVyIGFuZCBzb21lIHRvb2xzLgpBZGQgZmVhdHVyZSB0aGF0IGV4cG9ydCBkYXRhIHRvIGZpbGUuCk9wdGltaXplZCBtb2R1bGUsIHN1cHBvcnQgaGlkZSBzeXN0ZW0gbW9kdWxlcyBldGMuClBFIHNjYW5uZXIgc3VwcG9ydCBkb3dubG9hZCBtaWNyb3NvZnQgcGRiIGZpbGUKU3VwcG9ydCBkcmFnIGZpbGUgdG8gdmlldyB1bmxvY2sgZmlsZQpIYXBweSBDaGluZXNlIE5ldyBZZWFyIDIwMjIhCg==",
"appurl": "https://github.com/BlackINT3/OpenArk/releases"
}

[OpenArk::onActionCheckUpdate::::operator ()] [INFO] OpenArk is latest. 
[UNONE::ObLoadDriverW] [ERR] NtLoadDriver service:\Registry\Machine\System\CurrentControlSet\Services\OpenArkDrv64 err:c0000603
[Kernel::onClickKernelMode] [ERR] InstallDriver C:\Users\elvyo\AppData\Local\Temp\OpenArkDrv64.sys err 
[UNONE::ObLoadDriverW] [ERR] NtLoadDriver service:\Registry\Machine\System\CurrentControlSet\Services\OpenArkDrv64 err:c0000603
[Kernel::onClickKernelMode] [ERR] InstallDriver C:\Users\elvyo\AppData\Local\Temp\OpenArkDrv64.sys err 
[UNONE::ObLoadDriverW] [ERR] NtLoadDriver service:\Registry\Machine\System\CurrentControlSet\Services\OpenArkDrv64 err:c0000603
[Kernel::onClickKernelMode] [ERR] InstallDriver C:\Users\elvyo\AppData\Local\Temp\OpenArkDrv64.sys err 
[Kernel::ShowSystemNotify] [ERR] NotifyEnumProcess err 
[Kernel::ShowSystemNotify] [ERR] NotifyEnumThread err 
[Kernel::ShowSystemNotify] [ERR] NotifyEnumImage err 
[Kernel::ShowSystemNotify] [ERR] NotifyEnumRegistry err 
[UNONE::ObLoadDriverW] [ERR] NtLoadDriver service:\Registry\Machine\System\CurrentControlSet\Services\OpenArkDrv64 err:c0000603
[Kernel::onClickKernelMode] [ERR] InstallDriver C:\Users\elvyo\AppData\Local\Temp\OpenArkDrv64.sys err

**Comment by wang-xiaowu** [comment]
same question

**Comment by dan-hsc** [comment]
> same question

+1

**Comment by gusongen** [comment]
+1

**Comment by z2z63** [comment]
+1

**Comment by boyjunqiang** [comment]
+1

**Comment by tianhangj** [comment]
在22h2 22623中有同样的问题

**Comment by TensorABC** [comment]
+1

**Comment by songyuc** [comment]
+1

**Comment by Perseus-Cluster** [comment]
Windows 11 专业工作站版
22H2
22621.1105

同样点击内核模式没反应，期望开发者更新程序

**Comment by TheRainstorm** [comment]
win11 专业版 22621.1105，手动允许windows安全中心后，点击进入内核模式仍没作用

```
[OpenArk::onActionCheckUpdate::::operator ()] [INFO] OpenArk is latest. 
[UNONE::ObLoadDriverW] [ERR] NtLoadDriver service:\Registry\Machine\System\CurrentControlSet\Services\OpenArkDrv64 err:c0000603
[Kernel::onClickKernelMode] [ERR] InstallDriver C:\Users\xxx\AppData\Local\Temp\OpenArkDrv64.sys err 
```

**Comment by hd2y** [comment]
Windows 11 企业版 22H2 22621.1105

相同問題，期待回復。

**Comment by kimballlu** [comment]
一样的问题，希望修复

**Comment by zengchen233** [comment]
> Copyright (C) 2019 BlackINT3 https://github.com/BlackINT3/OpenArk [UNONE::FsReadFileDataW] [WARN] C:\Users\elvyo\AppData\Roaming\OpenArk\console\history.txt is empty file [unknown:0][WARN]QMetaObject::invokeMethod: No such method QWidget::onRefresh() [ArkDrvApi::Process::OpenProcess] [ERR] OpenProcess by Kernel pid:4 err:2 [ArkDrvApi::Process::OpenProcess] [ERR] OpenProcess by Kernel pid:4 err:2 [OpenArk::onActionCheckUpdate] [INFO] requset server:http://file.blackint3.com:88/openark/version.txt [OpenArk::onActionCheckUpdate::::operator ()] [INFO] local appver:1.2.2, build:202201282330 [OpenArk::onActionCheckUpdate::::operator ()] [INFO] server responsed:{ "err": 0, "appver": "1.2.2", "appbd": "202201282330", "appcl": "5aKe5Yqg6LCD6K+V56ym5Y+36K6+572u44CB5byA5Y+R5LqG5Zu95YaF5Yqg6YCf6ZWc5YOP6IqC54K5Cueoi+W6j+aUr+aMgeWcqOe6v+WNh+e6pwrlt6Xlhbfnm67lvZXmlK/mjIHkv67mlLnjgIHlop7liqDkuIDkupvlt6XlhbcK5pSv5oyB5pWw5o2u5a+85Ye65Yqf6IO977yM5L6L5aaC54Ot6ZSu44CB6amx5Yqo5YiX6KGo562JCuafpeeci+i/m+eoi+aooeWdl+aXtuWPr+i/h+a7pOezu+e7n+aooeWdlwpQReaJq+aPj+WZqOaUr+aMgeS4i+i9veW+rui9r3BkYuespuWPt+aWh+S7tgrmlK/mjIHmi5bmi73mlofku7bmn6XnnIvmlofku7bljaDnlKgK5paw5bm05b+r5LmQIDIwMjLvvIEKLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tCkFkZCBkZWJ1ZyBzeXN0ZW0gYW5kIGNuLW1pcnJvciByZXBvIGZlYXR1cmVzLgpBZGQgb25saW5lIHVwZ3JhZGUgZmVhdHVyZS4KQWRkIGNoYW5nZSByZXZlcnNlIHRvb2wgZm9sZGVyIGFuZCBzb21lIHRvb2xzLgpBZGQgZmVhdHVyZSB0aGF0IGV4cG9ydCBkYXRhIHRvIGZpbGUuCk9wdGltaXplZCBtb2R1bGUsIHN1cHBvcnQgaGlkZSBzeXN0ZW0gbW9kdWxlcyBldGMuClBFIHNjYW5uZXIgc3VwcG9ydCBkb3dubG9hZCBtaWNyb3NvZnQgcGRiIGZpbGUKU3VwcG9ydCBkcmFnIGZpbGUgdG8gdmlldyB1bmxvY2sgZmlsZQpIYXBweSBDaGluZXNlIE5ldyBZZWFyIDIwMjIhCg==", "appurl": "https://github.com/BlackINT3/OpenArk/releases" }
> 
> [OpenArk::onActionCheckUpdate::::operator ()] [INFO] OpenArk is latest. [UNONE::ObLoadDriverW] [ERR] NtLoadDriver service:\Registry\Machine\System\CurrentControlSet\Services\OpenArkDrv64 err:c0000603 [Kernel::onClickKernelMode] [ERR] InstallDriver C:\Users\elvyo\AppData\Local\Temp\OpenArkDrv64.sys err [UNONE::ObLoadDriverW] [ERR] NtLoadDriver service:\Registry\Machine\System\CurrentControlSet\Services\OpenArkDrv64 err:c0000603 [Kernel::onClickKernelMode] [ERR] InstallDriver C:\Users\elvyo\AppData\Local\Temp\OpenArkDrv64.sys err [UNONE::ObLoadDriverW] [ERR] NtLoadDriver service:\Registry\Machine\System\CurrentControlSet\Services\OpenArkDrv64 err:c0000603 [Kernel::onClickKernelMode] [ERR] InstallDriver C:\Users\elvyo\AppData\Local\Temp\OpenArkDrv64.sys err [Kernel::ShowSystemNotify] [ERR] NotifyEnumProcess err [Kernel::ShowSystemNotify] [ERR] NotifyEnumThread err [Kernel::ShowSystemNotify] [ERR] NotifyEnumImage err [Kernel::ShowSystemNotify] [ERR] NotifyEnumRegistry err [UNONE::ObLoadDriverW] [ERR] NtLoadDriver service:\Registry\Machine\System\CurrentControlSet\Services\OpenArkDrv64 err:c0000603 [Kernel::onClickKernelMode] [ERR] InstallDriver C:\Users\elvyo\AppData\Local\Temp\OpenArkDrv64.sys err

+1

**Comment by zengchen233** [comment]
+1

**Comment by sdegongzuo** [comment]
+1进入内核模式加载驱动报错

**Comment by stop-bullshit** [comment]
加README 的QQ群获取最新预览版

**Comment by ken515** [comment]
> 加README 的QQ群获取最新预览版

加了。一直没人审核通过

**Comment by hb-0** [comment]
+1

**Comment by BlackINT3** [comment]
v1.3.0 fixed, try it.

**Comment by Sungsym** [comment]
+1

**Comment by Sungsym** [comment]
Windows 10 专业版 19045.3208 22H2 +1

**Comment by jayChoa** [comment]
[UNONE::ObLoadDriverW] [ERR] NtLoadDriver service:\Registry\Machine\System\CurrentControlSet\Services\OpenArkDrv64 err:c0000603
[Kernel::onClickKernelMode] [ERR] InstallDriver C:\Users\lxk\AppData\Roaming\OpenArk\kernel\OpenArkDrv64.sys err 

version：OpenArk-v1.3.0 OpenArk64.exe

![image](https://github.com/BlackINT3/OpenArk/assets/128114062/0da55350-35e5-4e7e-b12f-f9f128399e59)

**Comment by MagpieFourtyTwo** [comment]
Same problem over here:
- Entering kernel mode is not possible, throws an error in console (see below)
- the requested driver's file "OpenArkDrv64.sys" is missing
- the folder "%APPDATA%\OpenArk\kernel" is empty
- 
Please provide the missing driver file - and if possible in English, cause my CN got a little rusty over time ...  ;)

```
OpenArk Console
Copyright (C) 2019 BlackINT3 https://github.com/BlackINT3/OpenArk
[UNONE::FsReadFileDataW] [WARN] D:\Users\<USERNAME>\AppData\Roaming\OpenArk\console\history.txt is empty file
[ArkDrvApi::Process::OpenProcess] [ERR] OpenProcess by Kernel pid:4 err:2 
[ArkDrvApi::Process::OpenProcess] [ERR] OpenProcess by Kernel pid:4 err:2 
[OpenArk::onActionCheckUpdate] [INFO] requset server:http://file.blackint3.com:88/openark/version.txt 
[OpenArk::onActionCheckUpdate::::operator ()] [INFO] local appver:1.3.0, build:202302270720 
[OpenArk::onActionCheckUpdate::::operator ()] [INFO] server responsed:{
"err": 0,
"appver": "1.3.0",
"appbd": "202302271420",
"appcl": "6L+b56iL566h55CG5aKe5by677yM6Ieq5Yqo5Yi35paw77yM5pSv5oyB5ouW5Yqo6YCJ5oup56qX5Y+jCuWGheaguOWinuWKoFNTRFQvU2hhZG93L1dGUC9GaWx0ZXIvTWluaWZpbHRlci9UaW1lcuetieWkmuenjeWbnuiwgwrng63plK7mlK/mjIFXaW4xMQrlt6XlhbflupPlkIjlubbvvIzmm7TmlrDmjaLku6PvvIzmlK/mjIHmn6Xor6IK5omr5o+P5Zmo5aKe5YqgRUxG44CB5pmu6YCa5paH5Lu25omr5o+PCuWinuWKoOaVsOWtpuiuoeeul+etiee8lueoi+WKqeaJiwrlkITnp41CVUfkv67lpI3vvIzlkITnp43orrDkuI3muIXnmoTlip/og70K5pe26ZqU5LiA5bm077yM5Y+q6IO96K+077yMR29vZCBMdWNrIDIwMjPvvIEKLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tCkltcG92ZWQgcHJvY2VzcyBtYW5hZ2VyLCByZWZyZXNoIGF1dG9tYXRpY2FsbHkuCkFkZGVkIGtlcm5lbCBmZWF0dXJlcywgU1NEVC9TaGFkb3cvV0ZQL0ZpbHRlci9NaW5pZmlsdGVyL1RpbWVyIGV0Yy4KQWRkZWQgZW51bSBob3RrZXkgZm9yIHdpbjExLgpBZGRlZCB0b29scyByZXBvLCBzZWFyY2ggc3VwcG9ydGVkLgpBZGRlZCBFTEYvRklMRSBzY2FubmVyIC4KQWRkZWQgbWF0Y2ggY2FjdWxhdG9yIGluIGNvZGVraXRzLgpCdWdmaXhlZCBhbmQgb3RoZXIgZmVhdHVyZXMuCkdvb2QgTHVjayAyMDIzIQo=",
"appurl": "https://github.com/BlackINT3/OpenArk/releases"
}

[Kernel::ParseKernelSymbol] [INFO] PDB: D:\Users\<USERNAME>\AppData\Roaming\OpenArk\symbols\fltMgr.pdb\C6B7358770920641714F8F39943309AC1\fltMgr.pdb 
[Kernel::ParseKernelSymbol] [INFO] PDB: D:\Users\<USERNAME>\AppData\Roaming\OpenArk\symbols\netio.pdb\4EE18C895B06AFCE34AC7F0F7C5862E31\netio.pdb 
[Kernel::ParseKernelSymbol] [INFO] PDB: D:\Users\<USERNAME>\AppData\Roaming\OpenArk\symbols\ntkrnlmp.pdb\606FF669409B00F7FC8C61A9C16701291\ntkrnlmp.pdb 
[Kernel::ParseKernelSymbol] [INFO] PDB: D:\Users\<USERNAME>\AppData\Roaming\OpenArk\symbols\win32kfull.pdb\151C3FD156383785149071174DFF74601\win32kfull.pdb 
[UNONE::ObLoadDriverW] [ERR] NtLoadDriver service:\Registry\Machine\System\CurrentControlSet\Services\OpenArkDrv64 err:c0000603
[Kernel::onClickKernelMode] [ERR] InstallDriver D:\Users\<USERNAME>\AppData\Roaming\OpenArk\kernel\OpenArkDrv64.sys err 
```

**Comment by MagpieFourtyTwo** [comment]
I am BTW using Windows 10 Pro 22H2 Build 19045.3570.
