### ISSUE TITLE
扫描器的修改时间和访问时间搞反了吧？

### ISSUE THREAD

**Issue by SlackXiao** [BlackINT3/OpenArk#107]
扫描器的修改时间和访问时间搞反了吧？

**Comment by BlackINT3** [comment]
Thanks. v1.3.0 fixed

**Comment by Masaiki** [comment]
> Thanks. v1.3.0 fixed

Sorry to bother. Will the 1.3.0 version be released soon?
不好意思打扰了 请问 1.3.0 版本会很快发布吗

**Comment by BlackINT3** [comment]
> 

https://github.com/BlackINT3/OpenArk/releases/tag/v1.3.0 released.

close it.
