### ISSUE TITLE
64 位 和 32位 分开提供

### ISSUE THREAD

**Issue by wordpure** [BlackINT3/OpenArk#111]
希望 64 位和 32 位的安装包可以像之前一样分开提供，只下载需要的位数，同时方便 Scoop 之类的软件管理器检测更新和处理。

![1.3.0](https://user-images.githubusercontent.com/68013962/222343063-a51c6be3-f761-405a-bead-5e7634006172.png)

![1.2.2](https://user-images.githubusercontent.com/68013962/222342987-c94ea4de-509e-49c1-a65a-5409ab56cdb5.png)

![Scoop 检测更新](https://user-images.githubusercontent.com/68013962/222342510-7039bd8e-1dcc-4275-b296-70f370b27b58.png)

**Comment by BlackINT3** [comment]
it done.
https://github.com/BlackINT3/OpenArk/releases
