### ISSUE TITLE
会考虑在加密算法功能里增加异或加密和凯撒加密吗

### ISSUE THREAD

**Issue by qingchunnh** [BlackINT3/OpenArk#114]
非常感谢作者制作的此软件，平时base64之类的用的比较多，不喜欢用网页在线的，但是发现没有异或和凯撒，所以想问一下会考虑增加这2种加密算法吗

**Comment by BlackINT3** [comment]
@qingchunnh em. it will be adding into future, but i think that you should use the professional crypto tool.

**Comment by qingchunnh** [comment]
> @qingchunnh em. it will be adding into future, but i think that you should use the professional crypto tool.

Thank you and apologies for my previous ignorance, I am now using `ToolsFx`.  
**thanks for developing OpenArk!**
