### ISSUE TITLE
进入内核，系统热键的热键列无显示内容

### ISSUE THREAD

**Issue by hyhr** [BlackINT3/OpenArk#119]
![openark_issue](https://user-images.githubusercontent.com/22883751/230816717-a2f820eb-f4b5-4d4e-8a7c-946af0639845.png)

win11家庭中文版
22H2
openArk：1.3.0

**Comment by a5066987** [comment]
+1 同样有这个问题，所有的热键都不显示热键列

![image](https://user-images.githubusercontent.com/13390857/232278241-1ab2cf6b-030d-4b6e-a1e6-7a57df72d5dd.png)

**Comment by BlackINT3** [comment]
win11最近更新导致，v1.3.2 Beta 已修复

**Comment by 907904228** [comment]
> win11最近更新导致，v1.3.2 Beta 已修复

请问在哪里下载beta版本

**Comment by HatsuneMona** [comment]
need v1.3.2 beta version, too.   where to download v1.3.2 beta?

我也需要 v1.3.2 beta版本的OpenArk，哪里可以下载到呢？

**Comment by cat9in9suit** [comment]
> win11最近更新导致，v1.3.2 Beta 已修复

去哪里能找到beta版本？

**Comment by BlackINT3** [comment]
@907904228 @HatsuneMona @cat9in9suit 
v1.3.2 近期会更新，Beta版进群获取

**Comment by hyhr** [comment]
如果是JetBrains系列的shift+F6失灵，把微软输入法卸了吧

**Comment by navee** [comment]
> 

不用卸载
![image](https://github.com/BlackINT3/OpenArk/assets/1822358/0ed2a372-aa30-4cd9-960f-b8ba106a1380)

**Comment by HarryChen001** [comment]
强啊，两位老哥，我就是遇到了shift+f10被占用了

**Comment by Les1ie** [comment]
> > 
> 
> 不用卸载 ![image](https://user-images.githubusercontent.com/1822358/250727453-0ed2a372-aa30-4cd9-960f-b8ba106a1380.png)

有用！！！！感谢

**Comment by tomuGo** [comment]
啥时候更新1.3.2啊

**Comment by Les1ie** [comment]
wz已收到您的邮件。

**Comment by a1392136** [comment]
> 如果是JetBrains系列的shift+F6失灵，把微软输入法卸了吧



> > 
> 
> 不用卸载 ![image](https://user-images.githubusercontent.com/1822358/250727453-0ed2a372-aa30-4cd9-960f-b8ba106a1380.png)

使用该方法解决了 idea 热键问题

**Comment by BlackINT3** [comment]
v1.3.2 relased.

> 啥时候更新1.3.2啊
