### ISSUE TITLE
“热键删除”报错了

### ISSUE THREAD

**Issue by waylau** [BlackINT3/OpenArk#123]
![image](https://github.com/BlackINT3/OpenArk/assets/3233966/f33415ed-e6c7-4a99-96a9-c9a2e993a034)

OpenArk 版本为 v1.3.2 Beta

我的电脑配置为：

* 版本	Windows 11 专业版
* 版本	22H2
* 安装日期	‎2023/‎4/‎3
* 操作系统版本	22621.1702
* 体验	Windows Feature Experience Pack 1000.22641.1000.0

**Comment by sn01615** [comment]
請問這個軟件安全嗎？

**Comment by Tea-NT** [comment]
> 請問這個軟件安全嗎？


@sn01615 我F11键突然没反应了，用这个找了一下， 第一次进内核模式需要联网的权限，然后看上去是会下载一些调试字符串文件，然后就正常进内核模式了。

F11键是AMDRSServ.exe占用了，估计是之前更新了电脑的显卡驱动。

感觉应该没问题，电脑装了火绒，和卡巴免费版，没报毒。我一般火绒常驻，控制联网权限，开始没给联网权限，进不了内核模式，点了左下角的按钮会出来控制台输出日志，看到需要下载文件，给了联网权限后下载后，后面就禁止联网了。

**Comment by BlackINT3** [comment]
@waylau Bug fixed in v1.3.2 beta.

**Comment by BlackINT3** [comment]
@sn01615 某群友說的是我在用愛發電...你說安全不... 2023-5-26 0:00

**Comment by waylau** [comment]
试了下QQ群里所发的 v1.3.2 beta（2023-05-30） 用了下，这个问题已经修复了。
