### ISSUE TITLE
win11的22H2-22621.1778这个版本不能用了，请求抽时间更新一下支持这个系统。

### ISSUE THREAD

**Issue by 15526441465** [BlackINT3/OpenArk#125]

**Comment by singularity2000** [comment]
确实，看不到热键了，如图
![image](https://github.com/BlackINT3/OpenArk/assets/61232355/e1998c6b-8c4a-4acd-a982-c04bb1d5f77e)

**Comment by 7ynstar** [comment]
+1 热键一栏显示为空

**Comment by 15526441465** [comment]
群里有支持这个版本的软件，我在群里拿到了。
