### ISSUE TITLE
Will not update 不会更新

### ISSUE THREAD

**Issue by YenLegion** [BlackINT3/OpenArk#127]
https://i.imgur.com/bFzTgpw.png

Connects to this IP address, makes .download and .old files. Does not upgrade. Checking if this upgrade is legitimate. Thank you. 

连接到此 IP 地址，生成 .download 和 .old 文件。不升级。检查此升级是否合法。谢谢。

https://i.imgur.com/EUrddby.png

https://i.imgur.com/sBRK2Cg.png

**Comment by BlackINT3** [comment]
@YenLegion It looks like a network problem. You can restore the .old file and then update again.
