### ISSUE TITLE
Win11进入内核模式失败

### ISSUE THREAD

**Issue by Joanh731** [BlackINT3/OpenArk#130]
[UNONE::ObLoadDriverW] [ERR] NtLoadDriver service:\Registry\Machine\System\CurrentControlSet\Services\OpenArkDrv64 err:c0000603
[Kernel::onClickKernelMode] [ERR] InstallDriver C:\Users\ljh\AppData\Roaming\OpenArk\kernel\OpenArkDrv64.sys err

**Comment by Axotot1** [comment]
掉签了，自己编译，然后打开nointegritychecks就可以了

**Comment by Mrasuna** [comment]
到那个文件夹里就会发现里面是空的

**Comment by BlackINT3** [comment]
v1.3.2 released.
