### ISSUE TITLE
无法进入内核 0xC0000603

### ISSUE THREAD

**Issue by Axotot1** [BlackINT3/OpenArk#131]
> STATUS_IMAGE_CERT_REVOKED (0xC0000603): 证书已被颁发者直接吊销。

这个如何解决？
<details><summary>Details</summary>
<p>

[Kernel::ParseKernelSymbol] [INFO] PDB: C:\Users\axototl\AppData\Roaming\OpenArk\symbols\fltMgr.pdb\BDB830D5AD37A0994727A90DE1D97BA41\fltMgr.pdb 
[Kernel::ParseKernelSymbol] [INFO] PDB: C:\Users\axototl\AppData\Roaming\OpenArk\symbols\netio.pdb\3F9ECB65540A5A8E8692CBC336B7A18F1\netio.pdb 
[Kernel::ParseKernelSymbol] [INFO] PDB: C:\Users\axototl\AppData\Roaming\OpenArk\symbols\ntkrnlmp.pdb\BBCA518265E9D831935C4FC58E2542ED1\ntkrnlmp.pdb 
[Kernel::ParseKernelSymbol] [INFO] PDB: C:\Users\axototl\AppData\Roaming\OpenArk\symbols\win32kfull.pdb\57313C081646785566423F6ADCBBAF3A1\win32kfull.pdb 
[UNONE::ObLoadDriverW] [ERR] NtLoadDriver service:\Registry\Machine\System\CurrentControlSet\Services\OpenArkDrv64 err:c0000603
[Kernel::onClickKernelMode] [ERR] InstallDriver C:\Users\axototl\AppData\Roaming\OpenArk\kernel\OpenArkDrv64.sys err 

</p>
</details>

**Comment by BlackINT3** [comment]
v1.3.2 released.
