### ISSUE TITLE
win11进入内核模式无响应

### ISSUE THREAD

**Issue by bruce-pang** [BlackINT3/OpenArk#133]
win11进入内核模式无响应

**Comment by yeziyezi** [comment]
同样的问题，打开控制台报错
`
[Kernel::ParseKernelSymbol] [INFO] PDB: C:\Users\xxx\AppData\Roaming\OpenArk\symbols\fltMgr.pdb\969A6F3F7B6B03139ED9D16D82046A491\fltMgr.pdb 
[Kernel::ParseKernelSymbol] [INFO] PDB: C:\Users\xxx\AppData\Roaming\OpenArk\symbols\netio.pdb\799807D5933281BEF94756ED241F8BFC1\netio.pdb 
[Kernel::ParseKernelSymbol] [INFO] PDB: C:\Users\xxx\AppData\Roaming\OpenArk\symbols\ntkrnlmp.pdb\A4FD849F9DB057DADB17916E3C0529DE1\ntkrnlmp.pdb 
[Kernel::ParseKernelSymbol] [INFO] PDB: C:\Users\xxx\AppData\Roaming\OpenArk\symbols\win32kfull.pdb\91CAD3CDC03F87ED758E1AD49133BB711\win32kfull.pdb 
[UNONE::ObLoadDriverW] [ERR] NtLoadDriver service:\Registry\Machine\System\CurrentControlSet\Services\OpenArkDrv64 err:c0000603
[Kernel::onClickKernelMode] [ERR] InstallDriver C:\Users\xxx\AppData\Roaming\OpenArk\kernel\OpenArkDrv64.sys err 
`

**Comment by jilliss** [comment]
+1 一样的问题，希望作者有时间的话，麻烦修复下这个问题 @BlackINT3

**Comment by Lingchen218** [comment]
+1 一样的问题，希望作者有时间的话，麻烦修复下这个问题

**Comment by xtay573269555** [comment]
系统环境：
```
版本	Windows 11 专业工作站版
版本	22H2
安装日期	‎2023/‎1/‎6
操作系统版本	22621.1992
体验	Windows Feature Experience Pack 1000.22644.1000.0
```

报错信息：
```
[Kernel::ParseKernelSymbol] [INFO] PDB: C:\Users\zfr\AppData\Roaming\OpenArk\symbols\fltMgr.pdb\969A6F3F7B6B03139ED9D16D82046A491\fltMgr.pdb 
[Kernel::ParseKernelSymbol] [INFO] PDB: C:\Users\zfr\AppData\Roaming\OpenArk\symbols\netio.pdb\799807D5933281BEF94756ED241F8BFC1\netio.pdb 
[Kernel::ParseKernelSymbol] [INFO] PDB: C:\Users\zfr\AppData\Roaming\OpenArk\symbols\ntkrnlmp.pdb\A4FD849F9DB057DADB17916E3C0529DE1\ntkrnlmp.pdb 
[Kernel::ParseKernelSymbol] [INFO] PDB: C:\Users\zfr\AppData\Roaming\OpenArk\symbols\win32kfull.pdb\91CAD3CDC03F87ED758E1AD49133BB711\win32kfull.pdb 
[Kernel::onClickKernelMode] [ERR] InstallDriver C:\Users\zfr\AppData\Roaming\OpenArk\kernel\OpenArkDrv64.sys err 
```

**Comment by LingerJAB** [comment]
+1 一样的问题，win11专业版进不去！！！！

**Comment by BlackINT3** [comment]
v1.3.2 released.
