### ISSUE TITLE
无法进入内核

### ISSUE THREAD

**Issue by H4ckBu7eer-EX** [BlackINT3/OpenArk#134]
错误日志：
[UNONE::ObLoadDriverW] [ERR] NtLoadDriver service:\Registry\Machine\System\CurrentControlSet\Services\OpenArkDrv64 err:c0000603
[Kernel::onClickKernelMode] [ERR] InstallDriver C:\Users\EX\AppData\Roaming\OpenArk\kernel\OpenArkDrv64.sys err 

c0000603
证书已被颁发者直接吊销

23年7月17日

**Comment by annisschen** [comment]
+1

**Comment by BlackINT3** [comment]
v1.3.2 released.
