### ISSUE TITLE
win11 无法进入内核模式

### ISSUE THREAD

**Issue by CodeQingKong** [BlackINT3/OpenArk#135]
[Kernel::ParseKernelSymbol] [INFO] PDB: C:\Users\Lenovo\AppData\Roaming\OpenArk\symbols\fltMgr.pdb\969A6F3F7B6B03139ED9D16D82046A491\fltMgr.pdb 
[Kernel::ParseKernelSymbol] [INFO] PDB: C:\Users\Lenovo\AppData\Roaming\OpenArk\symbols\netio.pdb\799807D5933281BEF94756ED241F8BFC1\netio.pdb 
[Kernel::ParseKernelSymbol] [INFO] PDB: C:\Users\Lenovo\AppData\Roaming\OpenArk\symbols\ntkrnlmp.pdb\A4FD849F9DB057DADB17916E3C0529DE1\ntkrnlmp.pdb 
[Kernel::ParseKernelSymbol] [INFO] PDB: C:\Users\Lenovo\AppData\Roaming\OpenArk\symbols\win32kfull.pdb\91CAD3CDC03F87ED758E1AD49133BB711\win32kfull.pdb 
[UNONE::ObLoadDriverW] [ERR] NtLoadDriver service:\Registry\Machine\System\CurrentControlSet\Services\OpenArkDrv64 err:c0000603
[Kernel::onClickKernelMode] [ERR] InstallDriver C:\Users\Lenovo\AppData\Roaming\OpenArk\kernel\OpenArkDrv64.sys err

**Comment by zhazhazsy** [comment]
同样问题

**Comment by HomengLau** [comment]
同样问题，编译下载编译环境失败

**Comment by codeking01** [comment]
我也是 进不去

**Comment by BlackINT3** [comment]
v1.3.2 released.
