### ISSUE TITLE
驱动的证书被吊销了

### ISSUE THREAD

**Issue by Axotot1** [BlackINT3/OpenArk#137]
![图片](https://github.com/BlackINT3/OpenArk/assets/99773418/58b75b10-6b99-4a86-aca8-fa73c2cc49d8)
证书被吊销了

**Comment by YuanWenHai** [comment]
同上，一样的问题。

**Comment by ddlong000** [comment]
亲测重签能用

**Comment by ezhengping** [comment]
@ddlong000 
如何重新签名？

**Comment by SmithAmway** [comment]
> 亲测重签能用

如何重新签名

**Comment by codeking01** [comment]
> 亲测重签能用

请问如何重签呀

**Comment by Miroxyz** [comment]
@ddlong000 
如何重新签名？
