### ISSUE TITLE
[问题反馈]点"进入内核模式"没反应，报错c0000603，如下

### ISSUE THREAD

**Issue by guchenfeng** [BlackINT3/OpenArk#138]
Manuals提示杀软需放行，可我这只有 火绒，也没有弹出任何提示
_系统信息：Win10 22H2 64位_
> [Kernel::ParseKernelSymbol] [INFO] PDB: C:\Users\***\AppData\Roaming\OpenArk\symbols\fltMgr.pdb\BDB830D5AD37A0994727A90DE1D97BA41\fltMgr.pdb 
[Kernel::ParseKernelSymbol] [INFO] PDB: C:\Users\***\AppData\Roaming\OpenArk\symbols\netio.pdb\3F9ECB65540A5A8E8692CBC336B7A18F1\netio.pdb 
[Kernel::ParseKernelSymbol] [INFO] PDB: C:\Users\***\AppData\Roaming\OpenArk\symbols\ntkrnlmp.pdb\BBCA518265E9D831935C4FC58E2542ED1\ntkrnlmp.pdb 
[Kernel::ParseKernelSymbol] [INFO] PDB: C:\Users\***\AppData\Roaming\OpenArk\symbols\win32kfull.pdb\57313C081646785566423F6ADCBBAF3A1\win32kfull.pdb 
[UNONE::ObLoadDriverW] [ERR] NtLoadDriver service:\Registry\Machine\System\CurrentControlSet\Services\OpenArkDrv64 err:c0000603
[Kernel::onClickKernelMode] [ERR] InstallDriver C:\Users\***\AppData\Roaming\OpenArk\kernel\OpenArkDrv64.sys err

**Comment by FlowAlive** [comment]
我遇到了同意的问题：
> [UNONE::ObLoadDriverW] [ERR] NtLoadDriver service:\Registry\Machine\System\CurrentControlSet\Services\OpenArkDrv64 err:c0000603
>[Kernel::onClickKernelMode] [ERR] InstallDriver C:\Users\sys\AppData\Roaming\OpenArk\kernel\OpenArkDrv64.sys err 

系统信息：
版本	Windows 11 专业版
版本	22H2
操作系统版本	22621.1992

**Comment by YufengSoft** [comment]
报错了：
[UNONE::ObLoadDriverW] [ERR] NtLoadDriver service:\Registry\Machine\System\CurrentControlSet\Services\OpenArkDrv64 err:c0000603

**Comment by fear-leap** [comment]
一样的报错,defender已关闭实时保护，且未安装其他杀毒软件。
[UNONE::ObLoadDriverW] [ERR] NtLoadDriver service:\Registry\Machine\System\CurrentControlSet\Services\OpenArkDrv64 err:c0000603
[Kernel::onClickKernelMode] [ERR] InstallDriver C:\Users\XXX\AppData\Roaming\OpenArk\kernel\OpenArkDrv64.sys err 

系统:windows11企业版
版本 21H1

**Comment by GanMocai** [comment]
一样的问题
版本	Windows 10 家庭中文版
版本号	22H2

**Comment by ESALTEREGO** [comment]
一样

**Comment by 1104949971** [comment]
[UNONE::ObLoadDriverW] [ERR] NtLoadDriver service:\Registry\Machine\System\CurrentControlSet\Services\OpenArkDrv64 err:c0000603
[Kernel::onClickKernelMode] [ERR] InstallDriver C:\Users\**\AppData\Roaming\OpenArk\kernel\OpenArkDrv64.sys err 
版本：Windows 10 家庭中文版
版本号：22H2

**Comment by hengxingstu** [comment]
[Kernel::ParseKernelSymbol] [INFO] PDB: C:\Users\hengxing\AppData\Roaming\OpenArk\symbols\fltMgr.pdb\969A6F3F7B6B03139ED9D16D82046A491\fltMgr.pdb 
[Kernel::ParseKernelSymbol] [INFO] PDB: C:\Users\hengxing\AppData\Roaming\OpenArk\symbols\netio.pdb\799807D5933281BEF94756ED241F8BFC1\netio.pdb 
[Kernel::ParseKernelSymbol] [INFO] PDB: C:\Users\hengxing\AppData\Roaming\OpenArk\symbols\ntkrnlmp.pdb\A4FD849F9DB057DADB17916E3C0529DE1\ntkrnlmp.pdb 
[Kernel::ParseKernelSymbol] [INFO] PDB: C:\Users\hengxing\AppData\Roaming\OpenArk\symbols\win32kfull.pdb\91CAD3CDC03F87ED758E1AD49133BB711\win32kfull.pdb 
[UNONE::ObLoadDriverW] [ERR] NtLoadDriver service:\Registry\Machine\System\CurrentControlSet\Services\OpenArkDrv64 err:c0000603
[Kernel::onClickKernelMode] [ERR] InstallDriver C:\Users\hengxing\AppData\Roaming\OpenArk\kernel\OpenArkDrv64.sys err 

同样的报错，Windows 11 Pro，22H2，Windows Feature Experience Pack 1000.22644.1000.0

**Comment by lin-mt** [comment]
版本	Windows 11 专业版
版本	22H2
安装日期	‎2023/‎5/‎8
操作系统版本	22621.1992
体验	Windows Feature Experience Pack 1000.22644.1000.0

一样的问题

**Comment by Escape-Zebra** [comment]
一样的问题

**Comment by phq19920106** [comment]
一样的问题：

**Comment by phq19920106** [comment]
[Kernel::ParseKernelSymbol] [INFO] PDB: C:\Users\phq\AppData\Roaming\OpenArk\symbols\fltMgr.pdb\BDB830D5AD37A0994727A90DE1D97BA41\fltMgr.pdb 
[Kernel::ParseKernelSymbol] [INFO] PDB: C:\Users\phq\AppData\Roaming\OpenArk\symbols\netio.pdb\AB48DD1F891D44F37D4883A131CE8E5F1\netio.pdb 
[Kernel::ParseKernelSymbol] [INFO] PDB: C:\Users\phq\AppData\Roaming\OpenArk\symbols\ntkrnlmp.pdb\06564D3477822C7D97F04852CBD5AFD61\ntkrnlmp.pdb 
[Kernel::ParseKernelSymbol] [INFO] Download: http://msdl.blackint3.com:88/download/symbols/ntkrnlmp.pdb/06564D3477822C7D97F04852CBD5AFD61/ntkrnlmp.pdb 
[HttpDownload::::operator ()] [INFO] Download failed, err:203, msg:Error transferring http://msdl.blackint3.com:88/download/symbols/ntkrnlmp.pdb/06564D3477822C7D97F04852CBD5AFD61/ntkrnlmp.pdb - server replied: Not Found 
[Kernel::ParseKernelSymbol] [ERR] LoadSymbol: C:\Users\phq\AppData\Roaming\OpenArk\symbols\ntkrnlmp.pdb\06564D3477822C7D97F04852CBD5AFD61\ntkrnlmp.pdb err 
[Kernel::ParseKernelSymbol] [INFO] PDB: C:\Users\phq\AppData\Roaming\OpenArk\symbols\win32kfull.pdb\B4137085DC07B1022513D7BFECA57E011\win32kfull.pdb 
[UNONE::ObLoadDriverW] [ERR] NtLoadDriver service:\Registry\Machine\System\CurrentControlSet\Services\OpenArkDrv64 err:c0000603
[Kernel::onClickKernelMode] [ERR] InstallDriver C:\Users\phq\AppData\Roaming\OpenArk\kernel\OpenArkDrv64.sys err

**Comment by lurui45** [comment]
[Kernel::ParseKernelSymbol] [INFO] PDB: C:\Users\daqo\AppData\Roaming\OpenArk\symbols\fltMgr.pdb\BDB830D5AD37A0994727A90DE1D97BA41\fltMgr.pdb 
[Kernel::ParseKernelSymbol] [INFO] PDB: C:\Users\daqo\AppData\Roaming\OpenArk\symbols\netio.pdb\AB48DD1F891D44F37D4883A131CE8E5F1\netio.pdb 
[Kernel::ParseKernelSymbol] [INFO] PDB: C:\Users\daqo\AppData\Roaming\OpenArk\symbols\ntkrnlmp.pdb\06564D3477822C7D97F04852CBD5AFD61\ntkrnlmp.pdb 
[Kernel::ParseKernelSymbol] [INFO] PDB: C:\Users\daqo\AppData\Roaming\OpenArk\symbols\win32kfull.pdb\B4137085DC07B1022513D7BFECA57E011\win32kfull.pdb 
[UNONE::ObLoadDriverW] [ERR] NtLoadDriver service:\Registry\Machine\System\CurrentControlSet\Services\OpenArkDrv64 err:c0000603
[Kernel::onClickKernelMode] [ERR] InstallDriver C:\Users\daqo\AppData\Roaming\OpenArk\kernel\OpenArkDrv64.sys err

**Comment by Rnreck** [comment]
一样的问题

**Comment by jxtcn** [comment]
+1

**Comment by ZHANG15210037977** [comment]
+1

**Comment by evil-plans** [comment]
+1

**Comment by guoqiang5277** [comment]
一样的问题，+1 。

**Comment by zippozeng** [comment]
一样的问题，+1 。

**Comment by BlackINT3** [comment]
进QQ群 706663529， 获取最新Beta版
注：后面Beta版都在QQ群发布，也可以在github等待发布稳定版。

Join QQ group 706663529 to get the latest Beta version.
Note: Beta versions will be released in the QQ group, and you can also wait for the stable version to be released on GitHub.

**Comment by BlackINT3** [comment]
v1.3.2 released.

**Comment by lidawei97688** [comment]
在事件查看器里发现了这个

日志名称:          Security
来源:            Microsoft-Windows-Security-Auditing
日期:            2024/3/6 23:25:20
事件 ID:         5038
任务类别:          System Integrity
级别:            信息
关键字:           审核失败
用户:            暂缺
计算机:           PANGWEI
描述:
代码完整性已确定文件的图像哈希无效。文件可能由于未授权的修改而毁坏，或者无效的哈希会指示可能的磁盘设备错误。

文件名:	\Device\HarddiskVolume3\Users\lidaw\AppData\Roaming\OpenArk\kernel\OpenArkDrv64.sys	
事件 Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Microsoft-Windows-Security-Auditing" Guid="{54849625-5478-4994-a5ba-3e3b0328c30d}" />
    <EventID>5038</EventID>
    <Version>0</Version>
    <Level>0</Level>
    <Task>12290</Task>
    <Opcode>0</Opcode>
    <Keywords>0x8010000000000000</Keywords>
    <TimeCreated SystemTime="2024-03-06T15:25:20.5299816Z" />
    <EventRecordID>224617</EventRecordID>
    <Correlation />
    <Execution ProcessID="4" ThreadID="4800" />
    <Channel>Security</Channel>
    <Computer>PANGWEI</Computer>
    <Security />
  </System>
  <EventData>
    <Data Name="param1">\Device\HarddiskVolume3\Users\lidaw\AppData\Roaming\OpenArk\kernel\OpenArkDrv64.sys</Data>
  </EventData>
</Event>
