### ISSUE TITLE
Subject: Issue: Compatibility with Windows 11 Version 22H2 and Request for Fix

### ISSUE THREAD

**Issue by OnceNever** [BlackINT3/OpenArk#139]
Dear BlackINT3,

I hope this message finds you well. I am an avid user of your open-source software, openArk, which has been incredibly helpful in listing all the keyboard shortcuts for the software installed on my computer. However, I recently encountered an issue after updating to Windows 11 Version 22H2.

The problem lies in the functionality to enter kernel mode, which seems to be affected by the recent Windows update. As a result, I am unable to utilize the feature to its fullest potential. Given the significance of this tool in my daily workflow, I find myself in great need of its capabilities to identify any conflicting or occupied keyboard shortcuts.

I truly appreciate the effort you have put into developing openArk and sharing it with the community. I would like to request your kind assistance in fixing the compatibility issue with Windows 11 Version 22H2 when you have the time available to do so. Your dedication to maintaining this project is highly regarded, and I sincerely thank you for considering this request.

If there is any additional information or testing I can assist with to help resolve this matter, please do not hesitate to let me know. Once again, thank you for your valuable contribution to the open-source community, and I look forward to continuing to benefit from your excellent software.

**Comment by walkonbench** [comment]
When I click the enter kernel mode button, the console will print the following error:

**Comment by walkonbench** [comment]
[Kernel::ParseKernelSymbol] [INFO] PDB: C:\Users\admin\AppData\Roaming\OpenArk\symbols\fltMgr.pdb\969A6F3F7B6B03139ED9D16D82046A491\fltMgr.pdb 
[Kernel::ParseKernelSymbol] [INFO] PDB: C:\Users\admin\AppData\Roaming\OpenArk\symbols\netio.pdb\799807D5933281BEF94756ED241F8BFC1\netio.pdb 
[Kernel::ParseKernelSymbol] [INFO] PDB: C:\Users\admin\AppData\Roaming\OpenArk\symbols\ntkrnlmp.pdb\A4FD849F9DB057DADB17916E3C0529DE1\ntkrnlmp.pdb 
[Kernel::ParseKernelSymbol] [INFO] PDB: C:\Users\admin\AppData\Roaming\OpenArk\symbols\win32kfull.pdb\91CAD3CDC03F87ED758E1AD49133BB711\win32kfull.pdb 
[UNONE::ObLoadDriverW] [ERR] NtLoadDriver service:\Registry\Machine\System\CurrentControlSet\Services\OpenArkDrv64 err:c0000603
[Kernel::onClickKernelMode] [ERR] InstallDriver C:\Users\admin\AppData\Roaming\OpenArk\kernel\OpenArkDrv64.sys err

**Comment by bling-yshs** [comment]
same
```
[Kernel::ParseKernelSymbol] [INFO] PDB: C:\Users\yshs\AppData\Roaming\OpenArk\symbols\fltMgr.pdb\969A6F3F7B6B03139ED9D16D82046A491\fltMgr.pdb 
[Kernel::ParseKernelSymbol] [INFO] PDB: C:\Users\yshs\AppData\Roaming\OpenArk\symbols\netio.pdb\799807D5933281BEF94756ED241F8BFC1\netio.pdb 
[Kernel::ParseKernelSymbol] [INFO] PDB: C:\Users\yshs\AppData\Roaming\OpenArk\symbols\ntkrnlmp.pdb\A4FD849F9DB057DADB17916E3C0529DE1\ntkrnlmp.pdb 
[Kernel::ParseKernelSymbol] [INFO] PDB: C:\Users\yshs\AppData\Roaming\OpenArk\symbols\win32kfull.pdb\91CAD3CDC03F87ED758E1AD49133BB711\win32kfull.pdb 
[Kernel::onClickKernelMode] [ERR] InstallDriver C:\Users\yshs\AppData\Roaming\OpenArk\kernel\OpenArkDrv64.sys err 
```

**Comment by jk20012001** [comment]
[Kernel::ParseKernelSymbol] [INFO] PDB: C:\Users\Administrator\AppData\Roaming\OpenArk\symbols\fltMgr.pdb\BDB830D5AD37A0994727A90DE1D97BA41\fltMgr.pdb 
[Kernel::ParseKernelSymbol] [INFO] PDB: C:\Users\Administrator\AppData\Roaming\OpenArk\symbols\netio.pdb\3F9ECB65540A5A8E8692CBC336B7A18F1\netio.pdb 
[Kernel::ParseKernelSymbol] [INFO] PDB: C:\Users\Administrator\AppData\Roaming\OpenArk\symbols\ntkrnlmp.pdb\BBCA518265E9D831935C4FC58E2542ED1\ntkrnlmp.pdb 
[Kernel::ParseKernelSymbol] [INFO] PDB: C:\Users\Administrator\AppData\Roaming\OpenArk\symbols\win32kfull.pdb\57313C081646785566423F6ADCBBAF3A1\win32kfull.pdb 
[UNONE::ObLoadDriverW] [ERR] NtLoadDriver service:\Registry\Machine\System\CurrentControlSet\Services\OpenArkDrv64 err:c0000603
[Kernel::onClickKernelMode] [ERR] InstallDriver C:\Users\Administrator\AppData\Roaming\OpenArk\kernel\OpenArkDrv64.sys err 



use OpenArk1.3.0
AMD Ryzen 5800X,   Win10 22H2 19045.3208

**Comment by MagpieFourtyTwo** [comment]
Same over here, as already reported in issue #105 (which may have been closed a little bit too fast) resp. [this comment](https://github.com/BlackINT3/OpenArk/issues/105#issuecomment-1768252912).

**Comment by MagpieFourtyTwo** [comment]
BTW: The "New version released, click to upgrade!" message from within OpenArk itself, seems to point to a previous version:
Although I clicked the blue message multiple times, I was not able to get promised build "202302271420".
Likewise the [zip](https://github.com/BlackINT3/OpenArk/releases/download/v1.3.0/OpenArk-v1.3.0.zip) *and* the [64bit exe](https://github.com/BlackINT3/OpenArk/releases/download/v1.3.0/OpenArk64.exe) file directly downloaded from [repository](https://github.com/BlackINT3/OpenArk/releases/tag/v1.3.0), although listed under "BUILD 202302271420", just contain resp. are the older "202302270720".

May of course be that just the build number is wrong (and therefore gives a false update message), but perhaps we're not getting the most recent (and probably already fixed) version ...?

**Comment by BlackINT3** [comment]
@OnceNever , v1.3.2 relased, you can try it.

**Comment by MagpieFourtyTwo** [comment]
At least with Windows 10 Pro Version 22H2 Build 19045.3636 it now works like a charm - thanks a lot!

**Comment by MagpieFourtyTwo** [comment]
BTW: The message "New version released" still appears, even though there is no new(er) one available for download - moreover the "new" version name shows tomorrow's date - may this be a timezome problem? 

![New version](https://github.com/BlackINT3/OpenArk/assets/9889015/cd88d740-e41d-4b48-a456-d20afabc5faf)

**Comment by BlackINT3** [comment]
> BTW: The message "New version released" still appears, even though there is no new(er) one available for download - moreover the "new" version name shows tomorrow's date - may this be a timezome problem?

You are right, it's time zone bug. I fixed and rereleased v1.3.2, you can try it. :)

**Comment by MagpieFourtyTwo** [comment]
Looks good - although this one should have been 1.3.3, shouldn't it?  ;)
However, after updating, the message is gone. Fine!

**Comment by OnceNever** [comment]
After updating to the new version, it works very well. Thanks for your support. :)
