### ISSUE TITLE
windows 10 专业版 22H2  无法进入内核

### ISSUE THREAD

**Issue by githubb000** [BlackINT3/OpenArk#141]
点击进入内核提示报错，信息如下：
[Kernel::ParseKernelSymbol] [INFO] PDB: C:\Users\xxx\AppData\Roaming\OpenArk\symbols\fltMgr.pdb\BDB830D5AD37A0994727A90DE1D97BA41\fltMgr.pdb 
[Kernel::ParseKernelSymbol] [INFO] PDB: C:\Users\xxx\AppData\Roaming\OpenArk\symbols\netio.pdb\3F9ECB65540A5A8E8692CBC336B7A18F1\netio.pdb 
[Kernel::ParseKernelSymbol] [INFO] PDB: C:\Users\xxx\AppData\Roaming\OpenArk\symbols\ntkrnlmp.pdb\BBCA518265E9D831935C4FC58E2542ED1\ntkrnlmp.pdb 
[Kernel::ParseKernelSymbol] [INFO] PDB: C:\Users\xxx\AppData\Roaming\OpenArk\symbols\win32kfull.pdb\57313C081646785566423F6ADCBBAF3A1\win32kfull.pdb 
[Kernel::onClickKernelMode] [ERR] InstallDriver C:\xxx\Magic\AppData\Roaming\OpenArk\kernel\OpenArkDrv64.sys err

**Comment by KirinRyuuri** [comment]
我有类似的问题，但是 Win11 22H2 22621
```shell
[Kernel::ParseKernelSymbol] [INFO] PDB: C:\Users\xxx\AppData\Roaming\OpenArk\symbols\fltMgr.pdb\969A6F3F7B6B03139ED9D16D82046A491\fltMgr.pdb 
[Kernel::ParseKernelSymbol] [INFO] PDB: C:\Users\xxx\AppData\Roaming\OpenArk\symbols\netio.pdb\799807D5933281BEF94756ED241F8BFC1\netio.pdb 
[Kernel::ParseKernelSymbol] [INFO] PDB: C:\Users\xxx\AppData\Roaming\OpenArk\symbols\ntkrnlmp.pdb\A4FD849F9DB057DADB17916E3C0529DE1\ntkrnlmp.pdb 
[Kernel::ParseKernelSymbol] [INFO] PDB: C:\Users\xxx\AppData\Roaming\OpenArk\symbols\win32kfull.pdb\91CAD3CDC03F87ED758E1AD49133BB711\win32kfull.pdb 
[UNONE::ObLoadDriverW] [ERR] NtLoadDriver service:\Registry\Machine\System\CurrentControlSet\Services\OpenArkDrv64 err:c0000603
[Kernel::onClickKernelMode] [ERR] InstallDriver C:\Users\xxx\AppData\Roaming\OpenArk\kernel\OpenArkDrv64.sys err 
```

已经请求了UAC，并且也通过了
WD和火绒都没有拦截日志，也加了白名单
内核完整性开启，不知道是不是和这个有关系

**Comment by asulada** [comment]
+1

**Comment by 1104949971** [comment]
+1

**Comment by LingerJAB** [comment]
+1

**Comment by YouAndTomorrow** [comment]
OpenArkDrv64 err:c0000603  签名原因,OpenArk使用的域联已经被拦截

具体可看 https://bbs.kanxue.com/thread-273316.htm

**Comment by wykjx1314** [comment]
> OpenArkDrv64 err:c0000603 签名原因,OpenArk使用的域联已经被拦截
> 
> 具体可看 https://bbs.kanxue.com/thread-273316.htm\
您好，不太了解openark使用了哪些域联，具体我应该如何修改driversipolicy.xml呢？

**Comment by yangfansun** [comment]
> OpenArkDrv64 err:c0000603 签名原因,OpenArk使用的域联已经被拦截
> 
> 具体可看 https://bbs.kanxue.com/thread-273316.htm

@YouAndTomorrow 请问具体是需要修改什么呢？

**Comment by BlackINT3** [comment]
v1.3.2 released.
