### ISSUE TITLE
进入内核模式失败

### ISSUE THREAD

**Issue by welfareHu** [BlackINT3/OpenArk#144]
![image](https://github.com/BlackINT3/OpenArk/assets/46522544/d3957b70-25ab-44fd-bfbf-938b3ee3998e)
[OpenArk::onActionCheckUpdate::::operator ()] [INFO] OpenArk is latest. 
[Kernel::ParseKernelSymbol] [INFO] PDB: C:\Users\welfareHu\AppData\Roaming\OpenArk\symbols\fltMgr.pdb\969A6F3F7B6B03139ED9D16D82046A491\fltMgr.pdb 
[Kernel::ParseKernelSymbol] [INFO] PDB: C:\Users\welfareHu\AppData\Roaming\OpenArk\symbols\netio.pdb\9EE7BD721D3DEF087E3DBC8DD61C95411\netio.pdb 
[Kernel::ParseKernelSymbol] [INFO] PDB: C:\Users\welfareHu\AppData\Roaming\OpenArk\symbols\ntkrnlmp.pdb\6DE4B1C1DC23B687940A233637EF56DC1\ntkrnlmp.pdb 
[Kernel::ParseKernelSymbol] [INFO] PDB: C:\Users\welfareHu\AppData\Roaming\OpenArk\symbols\win32kfull.pdb\4383C79AF165716D8125D4968D91E4551\win32kfull.pdb 
[UNONE::ObLoadDriverW] [ERR] NtLoadDriver service:\Registry\Machine\System\CurrentControlSet\Services\OpenArkDrv64 err:c0000603
[Kernel::onClickKernelMode] [ERR] InstallDriver C:\Users\welfareHu\AppData\Roaming\OpenArk\kernel\OpenArkDrv64.sys err

**Comment by ZHANG15210037977** [comment]
遇到同样问题


[Kernel::ParseKernelSymbol] [INFO] PDB: C:\Users\zgj\AppData\Roaming\OpenArk\symbols\fltMgr.pdb\969A6F3F7B6B03139ED9D16D82046A491\fltMgr.pdb 
[Kernel::ParseKernelSymbol] [INFO] PDB: C:\Users\zgj\AppData\Roaming\OpenArk\symbols\netio.pdb\9EE7BD721D3DEF087E3DBC8DD61C95411\netio.pdb 
[Kernel::ParseKernelSymbol] [INFO] PDB: C:\Users\zgj\AppData\Roaming\OpenArk\symbols\ntkrnlmp.pdb\6DE4B1C1DC23B687940A233637EF56DC1\ntkrnlmp.pdb 
[Kernel::ParseKernelSymbol] [INFO] PDB: C:\Users\zgj\AppData\Roaming\OpenArk\symbols\win32kfull.pdb\4383C79AF165716D8125D4968D91E4551\win32kfull.pdb 
[UNONE::ObLoadDriverW] [ERR] NtLoadDriver service:\Registry\Machine\System\CurrentControlSet\Services\OpenArkDrv64 err:c0000603
[Kernel::onClickKernelMode] [ERR] InstallDriver C:\Users\zgj\AppData\Roaming\OpenArk\kernel\OpenArkDrv64.sys err

**Comment by ddlong000** [comment]
经过分析是驱动证书过期了，需要重新驱动签名

**Comment by ezhengping** [comment]
根据 错误代码 C0000603 我找到了相关错误提示为：STATUS_IMAGE_CERT_REVOKED (0xC0000603): 证书已被颁发者直接吊销。

[UNONE::ObLoadDriverW] [ERR] NtLoadDriver service:\Registry\Machine\System\CurrentControlSet\Services\OpenArkDrv64 err:c0000603
响应的在coder.social中找到了该错误的解决办法。
https://coder.social/BlackINT3/OpenArk

**Comment by SmithAmway** [comment]
同样的问题，请问如何重新驱动签名呢？

**Comment by BlackINT3** [comment]
v1.3.2 released.
