### ISSUE TITLE
win11，点击进入内核模式无反应

### ISSUE THREAD

**Issue by merroneutron** [BlackINT3/OpenArk#145]
系统信息如下：
版本	Windows 11 家庭版
版本	22H2
安装日期	‎2022/‎10/‎25
操作系统版本	22621.2134
体验	Windows Feature Experience Pack 1000.22659.1000.0

openark控制台输出：
[Kernel::ParseKernelSymbol] [INFO] PDB: C:\Users\25014\AppData\Roaming\OpenArk\symbols\fltMgr.pdb\969A6F3F7B6B03139ED9D16D82046A491\fltMgr.pdb 
[Kernel::ParseKernelSymbol] [INFO] PDB: C:\Users\25014\AppData\Roaming\OpenArk\symbols\netio.pdb\9EE7BD721D3DEF087E3DBC8DD61C95411\netio.pdb 
[Kernel::ParseKernelSymbol] [INFO] PDB: C:\Users\25014\AppData\Roaming\OpenArk\symbols\ntkrnlmp.pdb\6DE4B1C1DC23B687940A233637EF56DC1\ntkrnlmp.pdb 
[Kernel::ParseKernelSymbol] [INFO] PDB: C:\Users\25014\AppData\Roaming\OpenArk\symbols\win32kfull.pdb\4383C79AF165716D8125D4968D91E4551\win32kfull.pdb 
[UNONE::ObLoadDriverW] [ERR] NtLoadDriver service:\Registry\Machine\System\CurrentControlSet\Services\OpenArkDrv64 err:c0000603
[Kernel::onClickKernelMode] [ERR] InstallDriver C:\Users\25014\AppData\Roaming\OpenArk\kernel\OpenArkDrv64.sys err

**Comment by benzBrake** [comment]
同样不能进入

**Comment by kingtonlee** [comment]
对， Windows 11根本用不了
