### ISSUE TITLE
win11无法进入内核模式

### ISSUE THREAD

**Issue by cli31** [BlackINT3/OpenArk#151]
win11无法进入内核模式；和之前被关闭的帖子一样的问题
![image](https://github.com/BlackINT3/OpenArk/assets/113943846/a1e63dbb-f8f2-4e5b-b417-5203eae2c017)

**Comment by Lin-Ye-Ye** [comment]
+1

**Comment by JackLiu7810** [comment]
+1

**Comment by ShawnWx2019** [comment]
+1

**Comment by Miroxyz** [comment]
+1

**Comment by hjhsjywanan** [comment]
+1

**Comment by liaohongyue** [comment]
+1

**Comment by BlackINT3** [comment]
进QQ群 706663529， 获取最新Beta版
注：后面Beta版都在QQ群发布，也可以在github等待发布稳定版。

Join QQ group 706663529 to get the latest Beta version.
Note: Beta versions will be released in the QQ group, and you can also wait for the stable version to be released on GitHub.

**Comment by c665** [comment]
Hi! could you please post the beta releases to a more accessible channel? It's hard to get a QQ account outside of China

**Comment by Jackleetheone** [comment]
> Hi! could you please post the beta releases to a more accessible channel? It's hard to get a QQ account outside of China你好！您能否将测试版发布到更易于访问的频道？在中国境外很难获得QQ帐户

哈哈，外国友人没有QQ吗，我挺多的，卖你一个，别干违法犯罪的就好，哈哈

**Comment by lzc-up** [comment]
> Hi! could you please post the beta releases to a more accessible channel? It's hard to get a QQ account outside of China

I can send email file to you

**Comment by mohanlq** [comment]
> win11无法进入内核模式;和之前被关闭的帖子一样的问题 ![image](https://user-images.githubusercontent.com/113943846/269547605-a1e63dbb-f8f2-4e5b-b417-5203eae2c017.png)

+1

**Comment by BlackINT3** [comment]
> Hi! could you please post the beta releases to a more accessible channel? It's hard to get a QQ account outside of China

@c665 You can join Discord channel chat with us.

https://discord.gg/5HwBqRwx
