### ISSUE TITLE
v1.3.0进入内核模式失败

### ISSUE THREAD

**Issue by godtang** [BlackINT3/OpenArk#152]
[Kernel::ParseKernelSymbol] [INFO] PDB: C:\Users\tmj\AppData\Roaming\OpenArk\symbols\fltMgr.pdb\BDB830D5AD37A0994727A90DE1D97BA41\fltMgr.pdb 
[Kernel::ParseKernelSymbol] [INFO] PDB: C:\Users\tmj\AppData\Roaming\OpenArk\symbols\netio.pdb\AB48DD1F891D44F37D4883A131CE8E5F1\netio.pdb 
[Kernel::ParseKernelSymbol] [INFO] PDB: C:\Users\tmj\AppData\Roaming\OpenArk\symbols\ntkrnlmp.pdb\79BE8C368BEC7DD9677EA9B355ACE7841\ntkrnlmp.pdb 
[Kernel::ParseKernelSymbol] [INFO] PDB: C:\Users\tmj\AppData\Roaming\OpenArk\symbols\win32kfull.pdb\E4F8E6FD1C189A77A7282D02D158A7971\win32kfull.pdb 
[UNONE::ObLoadDriverW] [ERR] NtLoadDriver service:\Registry\Machine\System\CurrentControlSet\Services\OpenArkDrv64 err:c0000603
[Kernel::onClickKernelMode] [ERR] InstallDriver C:\Users\tmj\AppData\Roaming\OpenArk\kernel\OpenArkDrv64.sys err 
![image](https://github.com/BlackINT3/OpenArk/assets/7802677/901c1309-521f-4b1f-81a3-114a32724f25)

**Comment by ZXYxc** [comment]
i meet the same question

**Comment by 1235789gzy1** [comment]
设置-更新和安全-恢复-高级启动
选择 禁用驱动程序签名强制执行 看看能不能进入内核模式

**Comment by DyingWallet** [comment]
![image](https://github.com/BlackINT3/OpenArk/assets/51984275/3ad16ee7-42f5-4e11-9cb3-5e76bb71658e)
遇到了类似的问题，系统：Win11 22H2 22621.2428

**Comment by BlackINT3** [comment]
进QQ群 706663529， 获取最新Beta版
注：后面Beta版都在QQ群发布，也可以在github等待发布稳定版。

Join QQ group 706663529 to get the latest Beta version.
Note: Beta versions will be released in the QQ group, and you can also wait for the stable version to be released on GitHub.

**Comment by thunder-sword** [comment]
> 进QQ群 706663529， 获取最新Beta版 注：后面Beta版都在QQ群发布，也可以在github等待发布稳定版。
> 
> Join QQ group 706663529 to get the latest Beta version. Note: Beta versions will be released in the QQ group, and you can also wait for the stable version to be released on GitHub.

这个群搜不到啊，老哥你试试看

**Comment by DyingWallet** [comment]
> 进QQ群 706663529， 获取最新Beta版 注：后面Beta版都在QQ群发布，也可以在github等待发布稳定版。
> 
> Join QQ group 706663529 to get the latest Beta version. Note: Beta versions will be released in the QQ group, and you can also wait for the stable version to be released on GitHub.

QQ上搜不到这个群

**Comment by godtang** [comment]
@DyingWallet @thunder-sword 用电脑搜，我用手机也搜不到
![image](https://github.com/BlackINT3/OpenArk/assets/7802677/ab7a662a-da64-4773-8152-dd515680ebba)

**Comment by Bluky-BlueSky** [comment]
> 设置-更新和安全-恢复-高级启动 选择 禁用驱动程序签名强制执行 看看能不能进入内核模式

使用这个方法成功进入内核模式，感谢
