### ISSUE TITLE
内核模式Minifilter禁用过滤器功能BUG

### ISSUE THREAD

**Issue by Gy4n** [BlackINT3/OpenArk#166]
如果过滤器中只存在POST回调时，patch 为return 1，会导致文件操作卡死，此时应该patch 为return 0

**Comment by Gy4n** [comment]
测试的是火绒剑 独立版 2.0.0.14

**Comment by Gy4n** [comment]
禁用这个IRP_MJ_CLEANUP_POST回调后，文件操作会被卡死。
![image](https://github.com/BlackINT3/OpenArk/assets/69465873/f6ae4dc2-b8b1-46cf-a611-65b8d84cb282)

**Comment by BlackINT3** [comment]
@Gy4n Thanks for feedbacking. It works in v1.3.6.
