### ISSUE TITLE
openark32 1.3.4 在 windows xp sp3 执行失败.   老版本1.3.2 能执行

### ISSUE THREAD

**Issue by kvjxhjwentnwm** [BlackINT3/OpenArk#168]
![1](https://github.com/BlackINT3/OpenArk/assets/121875753/d5bbff59-9c2b-452c-8603-66b4c1f02a84)

openark32 1.3.4 在 windows xp sp3 执行失败.   老版本1.3.2 能执行

**Comment by BlackINT3** [comment]
@kvjxhjwentnwm It works on xp sp3 that i've tested. u could download the latest released then try again?

**Comment by kvjxhjwentnwm** [comment]
很抱歉,我测试时用的是1.3.0.是这个版本打不开.

1.3.4没问题,实在抱歉
