### ISSUE TITLE
add zh_hk lang

### ISSUE THREAD

**Issue by samwell9624** [BlackINT3/OpenArk#171]
[openark_zh_hk.md](https://github.com/BlackINT3/OpenArk/files/14470558/openark_zh_hk.md)
rename openark_zh_hk.md to openark_zh_hk.ts

**Comment by BlackINT3** [comment]
@samwell9624 
Nice work.  adding into v1.3.6.

**Comment by BlackINT3** [comment]
@samwell9624 v1.3.6 released.
