### ISSUE TITLE
求助：下载后无法打开软件

### ISSUE THREAD

**Issue by broadth** [BlackINT3/OpenArk#174]
![image](https://github.com/BlackINT3/OpenArk/assets/59358074/c4c748ae-42a4-4c94-8a1e-ee73acea6d0f)

**Comment by BlackINT3** [comment]
@broadth Add into exclude list of AntiVirus product, for instance WindowsDefender, etc.

**Comment by broadth** [comment]
it doesn’t work
![image](https://github.com/BlackINT3/OpenArk/assets/59358074/03e44e9d-7c33-4087-a65b-3cbe8b1f1092)
> @broadth Add into exclude list of AntiVirus product, for instance WindowsDefender, etc.

**Comment by broadth** [comment]
it doesn’t work
![image](https://github.com/BlackINT3/OpenArk/assets/59358074/03e44e9d-7c33-4087-a65b-3cbe8b1f1092)
> @broadth Add into exclude list of AntiVirus product, for instance WindowsDefender, etc.

**Comment by broadth** [comment]
it doesn’t work
![image](https://github.com/BlackINT3/OpenArk/assets/59358074/201bc6de-c3f9-4aee-a7f7-5fe0d920e725)


> @broadth Add into exclude list of AntiVirus product, for instance WindowsDefender, etc.

**Comment by broadth** [comment]
it doesn’t work
![image](https://github.com/BlackINT3/OpenArk/assets/59358074/03e44e9d-7c33-4087-a65b-3cbe8b1f1092)
> @broadth Add into exclude list of AntiVirus product, for instance WindowsDefender, etc.

**Comment by broadth** [comment]
it doesn’t work
![image](https://github.com/BlackINT3/OpenArk/assets/59358074/201bc6de-c3f9-4aee-a7f7-5fe0d920e725)


> @broadth Add into exclude list of AntiVirus product, for instance WindowsDefender, etc.

**Comment by broadth** [comment]
After I exited the third-party antivirus software, it worked. thanks

> @broadth Add into exclude list of AntiVirus product, for instance WindowsDefender, etc.

**Comment by BlackINT3** [comment]
#175 duplicated.
