### ISSUE TITLE
1.3.4 在无网络的情况下难以进入内核模式

### ISSUE THREAD

**Issue by Mishasama** [BlackINT3/OpenArk#176]
![image](https://github.com/BlackINT3/OpenArk/assets/54498172/1b084f13-e458-4b7e-aee9-1978ea79ed70)

点击进入内核模式后，窗口会一直卡在这种状态长时间无法继续交互。但左下角的系统状态的显示还是照常在动，窗口也没有出现无响应的状况。
强行结束进程重新打开时，依旧没有进入内核模式。
但一旦恢复网络连接马上就能正常继续运作了。

我不懂编程语言无法直接检查代码是否有问题。
但经过短暂的测试，只要耐心等上好几分钟还是能进入内核模式的。怀疑是重试联网的次数太多，或是超时等待时间太长导致假死的现象。

请问为什么要在这一步强制使用网络？是 BUG 还是有什么特殊原因？

**Comment by BlackINT3** [comment]
@Mishasama The next version v1.3.6 will work as network unavaliable.

**Comment by Phoexina** [comment]
能不能直接下载这些.pdb文件自己放进去，你们的代码仓有提供这些文件的地方吗？我的工作环境无法连接这些网址。或者不依赖网络的1.3.6什么时候能发布

**Comment by BlackINT3** [comment]
@Mishasama @Phoexina v1.3.6 released.

**Comment by Mishasama** [comment]
Fixed confirmed.

**Comment by Mishasama** [comment]
Fixed confirmed.
