### ISSUE TITLE
1.0.8版本不能成功 删除热键

### ISSUE THREAD

**Issue by mostcool** [BlackINT3/OpenArk#19]
1.0.6版本还可以成功删除热键的，但1.0.8版本就不行了。
![image](https://user-images.githubusercontent.com/2172570/92187001-1ba6c300-ee8b-11ea-8e3c-4ad52b2f01d0.png)

**Comment by BlackINT3** [comment]
@mostcool Oh, thaks a lot, we fixed it. You can re-download it.

https://github.com/BlackINT3/OpenArk/releases

**Comment by mostcool** [comment]
> @mostcool Oh, thaks a lot, we fixed it. You can re-download it.
> 
> https://github.com/BlackINT3/OpenArk/releases

it's ok! thank you!
