### ISSUE TITLE
字体显示不全

### ISSUE THREAD

**Issue by handbye** [BlackINT3/OpenArk#21]
![image](https://user-images.githubusercontent.com/26617058/92548124-cb63a280-f288-11ea-88bf-0356f1b6a2a6.png)

**Comment by NanLake** [comment]
@handbye  这种改下字体大小就好了，设置成100%

![微信图片_20200909123545](https://user-images.githubusercontent.com/28210611/92554897-01108780-f299-11ea-902c-5893593a3664.png)

**Comment by BlackINT3** [comment]
d755d50 fixed
