### ISSUE TITLE
把AppData\Roaming\OpenArk下的symbols目录删掉，重新进入内核 还是无法查看热键

### ISSUE THREAD

**Issue by Ruling95** [BlackINT3/OpenArk#214]
详情请看一眼GIF，我的操作是不是正确。

![NVIDIA_Overlay_uPJRHqw1Mr](https://github.com/user-attachments/assets/6b31a8a0-6fff-474e-8b1f-a5598428c409)

**Comment by Ruling95** [comment]
操作系统版本信息。
![image](https://github.com/user-attachments/assets/dbf85e09-1488-446d-9b27-185df06ea5c4)

**Comment by zss823158062** [comment]
感觉是最新版windows11没适配；我的也是一样的

**Comment by Ruling95** [comment]
> https://www.kindyear.cn/archives/984/ 这里下载1.3.8beta版本即可或者前往QQ群下载

這个  1.3.8  bate 版本可以 了。
