### ISSUE TITLE
建议产生的文件放在exe的同级目录中

### ISSUE THREAD

**Issue by RC1844** [BlackINT3/OpenArk#23]
放在 AppData\Roaming\OpenArk 并不方便管理
![image](https://user-images.githubusercontent.com/14369275/93313718-69341000-f83b-11ea-8e11-a206e1e7a2cd.png)

还建议工具目录可以自定义
因为大家一般都会有自己的一个文件夹，用来存放这些特殊工具，
最好是使用相对路径，这样在移动硬盘中无需重新设置

**Comment by BlackINT3** [comment]
Thanks for feedback, this feature supported later.

**Comment by majorworld** [comment]
是的，放在同级目录的子文件夹里要好点，方便整个重新打压缩包

**Comment by BlackINT3** [comment]
@RC1844 

okay, it supported, wait for the next released.

ed656736b70af5c00d894ce3f36eeef36e2b4b30

**Comment by BlackINT3** [comment]
v1.1.0 released
