### ISSUE TITLE
DPI View Error 

### ISSUE THREAD

**Issue by kitty8904** [BlackINT3/OpenArk#24]
<img width="354" alt="error" src="https://user-images.githubusercontent.com/18622105/93470674-379b7180-f92d-11ea-87bf-142a50c0b885.png">

System Hook & etc view DPI View error?

my display 3840 x 2160  and text view size  150%

Button text is broken on 4K monitors

It should be patched to look normal on DPI

**Comment by BlackINT3** [comment]
Yes, we reproduced it. You can set font-size to percent 100 for a workaround. #21 
It will be fixed later. :)

**Comment by BlackINT3** [comment]
ok, d755d50 fixed
