### ISSUE TITLE
作者你好，能不能把内核-系统热键功能单独编译一个exe

### ISSUE THREAD

**Issue by majorworld** [BlackINT3/OpenArk#26]
作者你好，能不能把内核-系统热键功能单独编译一个exe，打开自动尝试进入内核模式，其他功能不要，你带上作者信息和自己的GitHub链接，我发布到一个论坛里，有部分用户只需要查看热键的功能的，非常感谢！

**Comment by BlackINT3** [comment]
@majorworld 你可以自行构建，参考如下文档。

https://github.com/BlackINT3/OpenArk/blob/master/doc/build-openark.md

**Comment by majorworld** [comment]
搞不来，啊哈哈
