### ISSUE TITLE
int3 大佬 你好，在VS2015 添加Nuget 源遇到问题

### ISSUE THREAD

**Issue by fcode520** [BlackINT3/OpenArk#27]
添加Nuget包仓库
http://nuget.blackint3.com:20001/api/odata
这个 地址 我这边 不论是否翻墙 都无法连接。
![image](https://user-images.githubusercontent.com/6696864/96062014-31b29500-0ec7-11eb-9e94-07c8a5d28251.png)
想确认下找个nuget源 是否还生效。

**Comment by BlackINT3** [comment]
@fcode520 
修复了，再试一次 :)

**Comment by fcode520** [comment]
感谢大佬，找个问题已经解决。确实服务器已经可以连上了。
但是我这边还有2个问题想和您确认一下
1：目前github上的ark 中使用的none 是否没有更新，自己编译none 在ark里面无法编译成功，显示有何变量没有定义。
none 目前打包成的nuget是1.0.2 。github 中 依赖的是1.0.3
2：使用blackint3 的nuget源 更新了 none 后。 在编译的时候 
报错：1>kernel\memory\memory.cpp(23): fatal error C1083: 无法打开包括文件: “QtUiTools/QtUiTools”: No such file or directory
编译手册中，提示 使用的是qt 5.6.2.
我在5.6.2中 未找到这个引用的文件。
而在5.9.7等版本中 确实包含了 qtuitools 文件。
想确认一下，目前您正常编译的时候 使用的是哪个版本。
非常感谢您 百忙之中给我的回复。
特别想把这个工具 自己编译成功。

**Comment by BlackINT3** [comment]
@fcode520 
1. none仓库已经更新。
2. 缺少QtUiTools的qt库也已更新，可根据编译文档 重新下载qt5.6.2-static-lib.zip

**Comment by fcode520** [comment]
@BlackINT3  大佬回复真是迅速 感谢大佬 我继续 尝试

**Comment by BlackINT3** [comment]
closed
