### ISSUE TITLE
windows Security会报毒

### ISSUE THREAD

**Issue by zhongguo1987** [BlackINT3/OpenArk#29]
下载最新的Release1.0.8版本，在Win10  20H2上，Windows Security会报存在病毒。上一版本就不存在这个问题

![image](https://user-images.githubusercontent.com/3292981/97151397-6b7a7a00-17aa-11eb-9ca8-ce5885ce9983.png)

**Comment by BlackINT3** [comment]
@zhongguo1987 因为是开源软件，并未向杀软厂商提交白名单，报毒很正常，手动加白即可。
若不放心，可自行审查代码并编译。

**Comment by zhongguo1987** [comment]
您好，上个Release，确实没有。所以猜测可能是哪块用法导致杀软误报

**Comment by bnyu** [comment]
Release1.1.0 安装包会报特洛伊木马

**Comment by zchazc** [comment]
我用 JAVA 编个鼠标连点工具都会报毒，所以建议“用人不疑，疑人不用”，愿意为安全原因下功夫的话建议自己过遍源码然后编译。
毕竟这是开源项目，花大功夫解决报毒问题是很奢侈的。
