### ISSUE TITLE
OpenArk1.0.8 32位 内核反汇编异常

### ISSUE THREAD

**Issue by YouAndToday** [BlackINT3/OpenArk#30]
内核->内存管理->内核读写

内核反汇编显示的寄存器存在x64的寄存器
![1](https://user-images.githubusercontent.com/51531424/97165905-5e1bba80-17bf-11eb-90e8-e9cbeafddd02.png)

**Comment by BlackINT3** [comment]
@YouAndToday Thanks for catch that.

**Comment by BlackINT3** [comment]
4fc29ff fixed.

**Comment by BlackINT3** [comment]
v1.1.0 released
