### ISSUE TITLE
怎么查看哪些系统端口被占用？

### ISSUE THREAD

**Issue by mostcool** [BlackINT3/OpenArk#34]

**Comment by BlackINT3** [comment]
describe you case in detail.

**Comment by mostcool** [comment]
有时候通过下面的方式并不能查出端口被哪个进程占用，所以问一下您这个工具里有没有更厉害点的方式来查找端口被占用的情况。
netstat -ano|findstr "22222"
tasklist|findstr "PID"

**Comment by mostcool** [comment]
@BlackINT3

**Comment by BlackINT3** [comment]
em, not support by far.
