### ISSUE TITLE
自定义工具目录

### ISSUE THREAD

**Issue by thanatos369** [BlackINT3/OpenArk#37]
逆向工具的工具目录，能实现自己定义么

**Comment by BlackINT3** [comment]
No support by far, but a workground that you could change the configuration (openark.ini) to the same folder with openark.exe.(#23 )

Also it will be adding into dev scheme.

**Comment by x-xiaolei** [comment]
Ok，thank you ！

**Comment by BlackINT3** [comment]
@thanatos369 

v1.2.2 已经支持修改目录。

**Comment by thanatos369** [comment]
谢谢！
