### ISSUE TITLE
Showsysnotify doesnt work on win7 7601

### ISSUE THREAD

**Issue by appleman1232** [BlackINT3/OpenArk#4]
[OpenArk::onActionCheckUpdate::::operator ()] [INFO] local appver:1.0.4, build:201907151833 
[OpenArk::onActionCheckUpdate::::operator ()] [INFO] OpenArk is latest. 
[Kernel::ShowSystemNotify] [ERR] NotifyEnumProcess err 
[Kernel::ShowSystemNotify] [ERR] NotifyEnumThread err 
[Kernel::ShowSystemNotify] [ERR] NotifyEnumImage err 
[Kernel::ShowSystemNotify] [ERR] NotifyEnumRegistry err 
[Kernel::ShowSystemNotify] [ERR] NotifyEnumProcess err 
[Kernel::ShowSystemNotify] [ERR] NotifyEnumThread err 
[Kernel::ShowSystemNotify] [ERR] NotifyEnumImage err 
[Kernel::ShowSystemNotify] [ERR] NotifyEnumRegistry err 
[Kernel::ShowSystemNotify] [ERR] NotifyEnumProcess err 
[Kernel::ShowSystemNotify] [ERR] NotifyEnumThread err 
[Kernel::ShowSystemNotify] [ERR] NotifyEnumImage err 
[Kernel::ShowSystemNotify] [ERR] NotifyEnumRegistry err 
[Kernel::InitKernelEntryView::::operator ()] [INFO] Enter KernelMode ok 
[Kernel::ShowSystemNotify] [ERR] NotifyEnumThread err 
[Kernel::ShowSystemNotify] [ERR] NotifyEnumRegistry err 
[Kernel::ShowSystemNotify] [ERR] NotifyEnumThread err 
[Kernel::ShowSystemNotify] [ERR] NotifyEnumRegistry err 
[Kernel::ShowSystemNotify] [ERR] NotifyEnumThread err 
[Kernel::ShowSystemNotify] [ERR] NotifyEnumRegistry err 
[Kernel::ShowSystemNotify] [ERR] NotifyEnumThread err 
[Kernel::ShowSystemNotify] [ERR] NotifyEnumRegistry err

**Comment by BlackINT3** [comment]
thanks for your feedback.
Process and Image Notify works indicated by log, i see you can check Registry/Thread Notify is existed?

**Comment by appleman1232** [comment]
My bad. thought this program checks all notify types like PCHunter.

Sorry. i had to check out the source but i didnt since i was lazy.
