### ISSUE TITLE
The text is small when applied to high-resolution screens/应用在高分辨率屏幕下文字很小

### ISSUE THREAD

**Issue by sleepybear1113** [BlackINT3/OpenArk#41]
An issue on appearance, the resolution is 4k, the text and components in the app are very small, which will affect the use less (but it doesn’t matter)

一个外观方面的 issue，分辨率为 4k，应用内的文字和组件都很小，会较小地影响使用（但也无所谓）

![image](https://user-images.githubusercontent.com/49073295/104160645-6bdef480-542c-11eb-906f-504f1e3a10e0.png)

**Comment by BlackINT3** [comment]
thanks, i'll try reproduce it later.

**Comment by yatounoneko** [comment]
你可以尝试在开启程序前设置一下，右键属性→兼容性→更改高DPI设置→勾选“代替高DPOI缩放行为”→选择“系统”

虽然是个临时方案并且可能会有点模糊，但字体过小的问题可以解决

**Comment by dalaocu** [comment]
I have encountered the same problem.

**Comment by BlackINT3** [comment]
duplicated #64
