### ISSUE TITLE
热键冲突无法检测到搜索输入法

### ISSUE THREAD

**Issue by burnningfire** [BlackINT3/OpenArk#44]
![image](https://user-images.githubusercontent.com/20715704/107904682-7179ae00-6f87-11eb-83a4-11ef304edaf1.png)
搜狗输入法占用全局热键Ctrl+shift+f切换繁体与简体，在系统热键中没有显示

**Comment by BlackINT3** [comment]
As IME use WindowHook, not support now.

**Comment by lulee007** [comment]
非常可恶，找了很久没找到
