### ISSUE TITLE
下载失败，错误：301

### ISSUE THREAD

**Issue by killgxlin** [BlackINT3/OpenArk#45]
[UNONE::FsReadFileDataW] [WARN] C:\Users\doit\AppData\Roaming\OpenArk\console\history.txt is empty file
[OpenArk::onActionCheckUpdate] [INFO] requset server:http://upt.blackint3.com/openark/version.txt 
[OpenArk::onActionCheckUpdate::::operator ()] [ERR] request http.err:0, net.err:1 
[OpenArk::onActionCheckUpdate] [INFO] requset server:http://upt.blackint3.com/openark/version.txt 
[OpenArk::onActionCheckUpdate::::operator ()] [ERR] request http.err:0, net.err:1 

无法解析upt.blackint3.com，导致工具无法安装

**Comment by BlackINT3** [comment]
@killgxlin it fixed.
