### ISSUE TITLE
OpenArk 现在可以通过 scoop 安装和更新了

### ISSUE THREAD

**Issue by wenmin92** [BlackINT3/OpenArk#46]
[scoop](https://scoop.sh/) 是一款 Windows 下流行的包管理器, 现在, OpenArk 已经可以使用 scoop 安装了:
```powershell
scoop install openark
```

https://github.com/lukesampson/scoop-extras/pull/5869

**Comment by BlackINT3** [comment]
Sounds COOL! 

`
1、install scoop
* Set-ExecutionPolicy RemoteSigned -scope CurrentUser
* Invoke-Expression (New-Object System.Net.WebClient).DownloadString('https://get.scoop.sh')

2、Add extras
* scoop bucket add extras

3、Install OpenArk
scoop install openark
`

BTW: run command above with powershell.

**Comment by wenmin92** [comment]
Update OpenArk:
```powershell
scoop update openark
```
Or, update all apps:
```powershell
scoop update *
```

**Comment by brucmao** [comment]
通过scoop按照后，怎么听过命令启动呢，我在pwsh输入openark提示找不到，按理说scoop安装后自动添加了环境变量

**Comment by wenmin92** [comment]
> 通过scoop按照后，怎么听过命令启动呢，我在pwsh输入openark提示找不到，按理说scoop安装后自动添加了环境变量

由于OpenArk不是命令行工具, 没有命令行选项, 所以没有注册OpenArk的可执行文件.

参考 https://github.com/lukesampson/scoop-extras/pull/5869#discussion_r597384811
