### ISSUE TITLE
进入内核模式后电脑的时间被重置了

### ISSUE THREAD

**Issue by Tegrisco** [BlackINT3/OpenArk#47]

**Comment by sjlei** [comment]
遇到同样的问题

**Comment by XZiar** [comment]
同样的问题。
![image](https://user-images.githubusercontent.com/15145384/122699961-420dd300-d1ff-11eb-8203-c9dd9174adee.png)
随手搜了一下似乎是这边定义的修改时间，而且结束后会恢复时间：
https://github.com/BlackINT3/OpenArk/blob/cf3d548b962f0f5cfb764c626f0c71b37f1ac06b/src/OpenArk/kernel/driver/driver.h#L77-L97
但根据日志，改变时间前时区先变了，导致后来时间显示不对，手动同步时间后恢复。

**Comment by hzqst** [comment]
我建议直接Patch掉CertVerifyTimeValidity：https://github.com/hzqst/FuckCertVerifyTimeValidity

**Comment by BlackINT3** [comment]
@Tegrisco @sjlei @XZiar 
v1.2.0 fixed.
