### ISSUE TITLE
进入内核模式后，看不到 shutdown 的回调，删除回调时，软件失去响应几秒钟后，自动退出了

### ISSUE THREAD

**Issue by hhs66317** [BlackINT3/OpenArk#48]

**Comment by BlackINT3** [comment]
@hhs66317 
目前shutdown回调不支持。
这个退出的问题能否重现？

**Comment by hhs66317** [comment]
前段时间没看邮箱，刚刚清理邮箱时才看到回复。

当前在Win10（企业版 1909）环境中，是无法进入内核模式的

通过KVM安装的WIN7X64虚拟机，点击进入内核模式，程序马上退出

**Comment by Kara-4search** [comment]
我可以复现 遇到相同问题了 winver 19042.1466

**Comment by Kara-4search** [comment]
> @hhs66317
> 目前shutdown回调不支持。
> 这个退出的问题能否重现？

目前是不支持删除回调的是吗

**Comment by BlackINT3** [comment]
v1.3.0 released
