### ISSUE TITLE
Add hold-file enum and unlock features，like unlocker（建议增加文件占用检测，以及解除进程对文件占用的功能）

### ISSUE THREAD

**Issue by hac425xxx** [BlackINT3/OpenArk#5]

**Comment by BlackINT3** [comment]
@hac425xxx  Please use english and we can communicate with community guys from wherever.

**Comment by BlackINT3** [comment]
Thanks for feedback, we'll add it later.

**Comment by BlackINT3** [comment]
v1.0.8 supported.
