### ISSUE TITLE
`Enter KernelMode` does not work on Windows 10 21H1

### ISSUE THREAD

**Issue by arshcaria** [BlackINT3/OpenArk#51]
`Enter KernelMode` does not work on Windows 10 21H1 (OS Build 19043.1110). Clicking the button has no effect.

![image](https://user-images.githubusercontent.com/3211106/125921523-09649c45-1c28-46ba-9959-da886ae2a1a7.png)

**Comment by BlackINT3** [comment]
v1.2.0 fixed.
