### ISSUE TITLE
麻烦作者适配一下 21H1

### ISSUE THREAD

**Issue by RemMai** [BlackINT3/OpenArk#52]
作者您好，我也是相当喜欢用这个小工具，麻雀虽小，五脏俱全。
作为开发人员我很需要这个软件，但是奈何自己的技术能力不过关，不懂C++。
所以恳请作者抽空适配一下21H1，谢谢。

**Comment by panhaoyu** [comment]
同求

**Comment by BlackINT3** [comment]
@RemMai 
v1.2.0 fixed.
