### ISSUE TITLE
系统热键，点击进入内核模式，会弹出某个公司的面试框！！！

### ISSUE THREAD

**Issue by MrWang5201314** [BlackINT3/OpenArk#53]
![image](https://user-images.githubusercontent.com/29561503/126138922-18d21ab6-30c6-47d2-a609-db559ab1baee.png)

**Comment by ssxwcz** [comment]
网易邮箱大师吧，检查下网易邮箱大师里面的日历有没有你设置的日程，不知道为啥现在openark点击进入内核会触发网易邮箱大师的日程提醒

**Comment by MrWang5201314** [comment]
确实在网易邮箱大师里面的日历里面找到设置的这个日程了，但是不知道为啥点击进入内核会触发了

**Comment by BlackINT3** [comment]
@MrWang5201314 
v1.2.0 fixed
