### ISSUE TITLE
无法进入内核模式

### ISSUE THREAD

**Issue by zz541843** [BlackINT3/OpenArk#54]
进入内核模式一直点没用，下了最新的也没用，没装那些软件，我都退掉了也进不去，没有任何异常，只是时间会被清零，但系统自己又获取回来了，以前都能用的，不知道咋回事

**Comment by YYforymj** [comment]
遇到了同样的问题，不知道是不是跟系统更新有关系，最近有更新系统，更新之前是可以用的，更新之后就不行了
<img width="435" alt="Snipaste_2021-07-28_12-02-45" src="https://user-images.githubusercontent.com/18638123/127261751-d708bf41-1560-4621-aac9-2b377729740f.png">

**Comment by zz541843** [comment]
@YYforymj 我觉得有可能，我现在两台电脑都无法进入内核模式，我的印象中1909的都可以进，我现在一台20H2，一台2004

**Comment by snsnsjsn** [comment]
我的也无法进入内核模式
![image](https://user-images.githubusercontent.com/11435527/127878720-bb763186-52d6-4e84-862b-8860b71faaa6.png)

**Comment by aengusjiang** [comment]
遇到同样问题

**Comment by 0nizuka** [comment]
Win10 专业版 [21H1] 点击内核模式控制台输出：
[UNONE::ObLoadDriverW] [ERR] NtLoadDriver service:\Registry\Machine\System\CurrentControlSet\Services\OpenArkDrv64 err:c0000603
[Kernel::onClickKernelMode] [ERR] InstallDriver C:\Users\*******\AppData\Local\Temp\OpenArkDrv64.sys err

**Comment by chinauncle** [comment]
版本	Windows 10 专业版
版本号	21H1
安装日期	‎2021/‎6/‎2
操作系统内部版本	19043.1110
体验	Windows Feature Experience Pack 120.2212.3530.0


[UNONE::ObLoadDriverW] [ERR] NtLoadDriver service:\Registry\Machine\System\CurrentControlSet\Services\OpenArkDrv64 err:c0000603
[Kernel::onClickKernelMode] [ERR] InstallDriver C:\Users\myl86\AppData\Local\Temp\OpenArkDrv64.sys err

**Comment by flyleave** [comment]
[UNONE::ObLoadDriverW] [ERR] NtLoadDriver service:\Registry\Machine\System\CurrentControlSet\Services\OpenArkDrv64 err:c0000603
[Kernel::onClickKernelMode] [ERR] InstallDriver C:\Users\lenovo\AppData\Local\Temp\OpenArkDrv64.sys err 
[UNONE::ObLoadDriverW] [ERR] NtLoadDriver service:\Registry\Machine\System\CurrentControlSet\Services\OpenArkDrv64 err:c0000603
[Kernel::onClickKernelMode] [ERR] InstallDriver C:\Users\lenovo\AppData\Local\Temp\OpenArkDrv64.sys err

**Comment by RekklessO** [comment]
我20h2也不行，现在我ctrl+f的热键不知道被谁占用了，现在什么软件都不能用搜索，烦死了

**Comment by wangkaish** [comment]
+1

**Comment by wenmin92** [comment]
> 我20h2也不行，现在我ctrl+f的热键不知道被谁占用了，现在什么软件都不能用搜索，烦死了

使用 spy++ 也可以定位快捷键占用 
参考: https://superuser.com/questions/11308/how-can-i-determine-which-process-owns-a-hotkey-in-windows/1204019#1204019

**Comment by andronoob** [comment]
#58

**Comment by BlackINT3** [comment]
v1.2.0 fixed.

**Comment by ezhengping** [comment]
根据 错误代码 C0000603 我找到了相关错误提示为：STATUS_IMAGE_CERT_REVOKED (0xC0000603): 证书已被颁发者直接吊销。
>[UNONE::ObLoadDriverW] [ERR] NtLoadDriver service:\Registry\Machine\System\CurrentControlSet\Services\OpenArkDrv64 err:c0000603
响应的在coder.social中找到了该错误的解决办法。
[https://coder.social/BlackINT3/OpenArk](https://coder.social/BlackINT3/OpenArk)

**Comment by codeking01** [comment]
解决措施，大家可以试一下：
 https://github.com/BlackINT3/OpenArk/issues/58?ref=https://githubhelp.com

**Comment by Jf710001011** [comment]
重启app对我有效
