### ISSUE TITLE
OPENARK无法打开内核

### ISSUE THREAD

**Issue by UTF-8zm** [BlackINT3/OpenArk#57]
[UNONE::FsReadFileDataW] [WARN] C:\Users\86178\AppData\Roaming\OpenArk\console\history.txt is empty file
![image](https://user-images.githubusercontent.com/89619630/131059204-975cbe5b-4536-478d-86e4-0692f1a76216.png)

**Comment by panhaoyu** [comment]
![image](https://user-images.githubusercontent.com/23495987/132206965-35fb746f-e67c-47e9-b0b8-4824097b407e.png)

Here's my error.

**Comment by wozaihu** [comment]
点击没反应，无法使用了

**Comment by zhpoo** [comment]
same here.

**Comment by ACodingJie** [comment]
期待修复

**Comment by xintongelement** [comment]
期待修复+1

**Comment by Difficulty-in-naming** [comment]
+1

**Comment by mouzou3791** [comment]
+1

**Comment by andronoob** [comment]
#58

**Comment by xixi36500** [comment]
我也遇到同样的问题

**Comment by tt545571022** [comment]
> ![image](https://user-images.githubusercontent.com/23495987/132206965-35fb746f-e67c-47e9-b0b8-4824097b407e.png)
> 
> Here's my error.

same here

**Comment by BlackINT3** [comment]
@all guys.
v1.2.0 fixed!

**Comment by joeaniu** [comment]
![image](https://github.com/BlackINT3/OpenArk/assets/2009190/552873db-0450-426c-8dc7-658154da992e)
在1.3.0里复现了这个问题，求助!
