### ISSUE TITLE
Memory Viewer: reading memory from non-image or invalid region shows last image

### ISSUE THREAD

**Issue by hzqst** [BlackINT3/OpenArk#6]
内存查看从无模块区域和无效区域读取内存会仍显示上一次的区域
![image](https://user-images.githubusercontent.com/12287588/87755817-4e90eb00-c83a-11ea-9c7d-54b540d4de66.png)

**Comment by BlackINT3** [comment]
@hzqst Thanks for catching that, it fixed.

**Comment by BlackINT3** [comment]
Issue be openning until new version release.

**Comment by BlackINT3** [comment]
Close, v1.0.8 fixed
