### ISSUE TITLE
win10内部版本19044.1320 错误识别为Win 11

### ISSUE THREAD

**Issue by binsee** [BlackINT3/OpenArk#60]
我的系统是 Win10  21H2 / 19044.1320 ，在OpenArk中错误识别为 Windows 11。
这个只是显示的操作系统名称错误，似乎不影响其他功能使用。

## 相关代码
https://github.com/BlackINT3/OpenArk/blob/8fc6aa1e29e858ed87938d4761e60812cee3e9c1/src/OpenArk/common/win-wrapper/win-wrapper.cpp#L709

## 相关截图
![image](https://user-images.githubusercontent.com/5285894/139724616-5503492b-5bf0-432e-97c6-09c970a699e6.png)
![image](https://user-images.githubusercontent.com/5285894/139724694-f47401b4-e632-408e-a2e3-696a1b0e11d0.png)

**Comment by BlackINT3** [comment]
@binsee  
Thanks，you can try the new released.

**Comment by binsee** [comment]
确认已经解决。
