### ISSUE TITLE
Win10 20H2 无法进入内核模式

### ISSUE THREAD

**Issue by ttbadr** [BlackINT3/OpenArk#61]
最新的1.2 无法进入内核模式
![image](https://user-images.githubusercontent.com/3127447/139799003-4614f0b0-955f-418f-b594-9fb1a6e30ae6.png)

**Comment by BlackINT3** [comment]
@ttbadr 

![image](https://user-images.githubusercontent.com/35478470/139863812-8bf6d1b2-df47-4888-b60f-87b481fdcd98.png)

杀毒软件放行试试

**Comment by ttbadr** [comment]
问题解决了，确实是杀毒软件的问题
