### ISSUE TITLE
字体很小，看着很费力，请求调整下

### ISSUE THREAD

**Issue by Mingtu2019** [BlackINT3/OpenArk#64]
字体很小，看着很费力，请求调整适配一下，谢谢大佬
![Snipaste_2021-11-30_13-36-34](https://user-images.githubusercontent.com/49590221/143991753-10c1a9e6-0d07-41ea-acbf-aa0d218597ce.png)

**Comment by mIgLLL** [comment]
高分辨率屏幕真的看的很痛苦呜呜呜

**Comment by Chandler-Lu** [comment]
![Snipaste_2022-02-21_15-05-14](https://user-images.githubusercontent.com/18322610/154905571-c946ac37-4007-49c1-b30f-758d7c9cf902.png)
win11 可以暂时先这么来，不过还是希望作者能适配高分屏啦~

**Comment by YangYuChina** [comment]
> ![Snipaste_2022-02-21_15-05-14](https://user-images.githubusercontent.com/18322610/154905571-c946ac37-4007-49c1-b30f-758d7c9cf902.png) win11 可以暂时先这么来，不过还是希望作者能适配高分屏啦~

好用！而且是个通用办法。感谢！

**Comment by sceraser** [comment]
要么糊要么小，唉

**Comment by BlackINT3** [comment]
试一下v1.3.0 显示如何？
