### ISSUE TITLE
按照document测试绑定器失败

### ISSUE THREAD

**Issue by lovingcowboy** [BlackINT3/OpenArk#66]
win7上按文档说明测试绑定器.
bat和vbs都显示无法找到脚本文件
请问脚本中的%root%变量跟系统环境变量中的Temp有关系的吗?
是否因为pc上的Temp环境变量修改过有关?

![Snipaste_2022-01-04_10-30-41](https://user-images.githubusercontent.com/9125855/148012076-f985be4a-5623-409b-9996-c8213fc90549.png)
"

**Comment by BlackINT3** [comment]
@lovingcowboy 
完整的脚本贴出来看看

**Comment by lovingcowboy** [comment]
就是按照文档说明里面的脚本
@echo off
echo shadow BAT running
pause>nul

**Comment by BlackINT3** [comment]
用start是异步执行，将start换成call，或者修正批处理执行逻辑。
