### ISSUE TITLE
PcHunter+ 显示 license 过期

### ISSUE THREAD

**Issue by Jackiexiao** [BlackINT3/OpenArk#68]
window11 系统

逆向工具有两个选项
1. pchunter 打开后显示加载驱动失败
2. pchunter + 显示 license 过期

此外，在window11上打开 openArk 字体非常小

**Comment by BlackINT3** [comment]
1、新版本会移除pchunter。 
2、屏幕分辨率是多少？

**Comment by Jackiexiao** [comment]
分辨率: 2880*1800

**Comment by BlackINT3** [comment]
duplicated #64
