### ISSUE TITLE
win2012 r2 kernel callback 显示不对， 系统热键显示不对，工具箱界面被挡住

### ISSUE THREAD

**Issue by zys0807** [BlackINT3/OpenArk#7]
1. kernel callback 用其它工具看，是有很多，我们的OARK显示只有一条
2.系统热键显示不对，显示有F21....F2N出现
3.工具箱界面显示有些问题

**Comment by Yamico** [comment]
![image](https://user-images.githubusercontent.com/63667585/89476896-71ba1500-d7be-11ea-8bb5-58e4981f6f21.png)
任务栏显示启动了窗口，但是界面无法显示

**Comment by BlackINT3** [comment]
@Yamico Can you reproduce that? give me more informations.
1、OS version （Win10, 1903 or 2004 eg...）
2、Minidump

**Comment by BlackINT3** [comment]
VK Code from there.
https://docs.microsoft.com/en-us/windows/win32/inputdev/virtual-key-codes

**Comment by BlackINT3** [comment]
Close，v1.0.8 fixed.
