### ISSUE TITLE
win11 22581 下系统热键显示不了了

### ISSUE THREAD

**Issue by toddchen2018** [BlackINT3/OpenArk#73]
win11自动升级到了22581
删除热键时发现里面显示内容空了
升级前使用都正常，应该是升级问题吧

**Comment by timnick-snow** [comment]
+1

**Comment by Bolov01** [comment]
22581.200版本同样的问题

**Comment by ssxwcz** [comment]
22H2 22621.1同样问题，报错信息如下
```log
[Kernel::onClickKernelMode] [INFO] Enter KernelMode ok 
[ArkDrvApi::IoControlDriver] [ERR] DeviceIoControl err:31 
```

**Comment by 1human** [comment]
同 
有个软件有个快捷键 ctrl+.  没法改，也不知道和哪个软件冲突了

**Comment by easyinplay** [comment]
一样的问题，进入内核模式也无法显示

**Comment by easyinplay** [comment]
![image](https://user-images.githubusercontent.com/4202001/176375420-b2de323e-b67d-4505-9e93-a080a9cab6b3.png)

**Comment by 1594853051** [comment]
+1

**Comment by BlackINT3** [comment]
v1.3.0 released
