### ISSUE TITLE
捆绑后的exe运行，显示找不到temp中的文件

### ISSUE THREAD

**Issue by Swagtimeao** [BlackINT3/OpenArk#77]
<img width="967" alt="image" src="https://user-images.githubusercontent.com/45483635/163950731-968596b4-bf73-490f-b0b0-45a64933d4f2.png">

**Comment by BlackINT3** [comment]
@Swagtimeao 
脚本怎么写的？%root%+相对路径，看你这种A目录应该就是%root%
