### ISSUE TITLE
帮助文档->CN->内核页面404

### ISSUE THREAD

**Issue by Lantern-r** [BlackINT3/OpenArk#8]
![image](https://user-images.githubusercontent.com/64698811/90355139-17526b80-e07e-11ea-9295-7ec285308589.png)

**Comment by BlackINT3** [comment]
Thanks, it fixed. https://openark.blackint3.com/manuals/CN/%E5%86%85%E6%A0%B8/%E6%9F%A5%E7%9C%8B%E8%A2%AB%E5%8D%A0%E7%94%A8%E7%9A%84%E7%B3%BB%E7%BB%9F%E7%83%AD%E9%94%AE/
