### ISSUE TITLE
不能进入内核模式

### ISSUE THREAD

**Issue by shadowfish07** [BlackINT3/OpenArk#81]
按进入内核模式没反应：

```
[UNONE::ObLoadDriverW] [ERR] NtLoadDriver service:\Registry\Machine\System\CurrentControlSet\Services\OpenArkDrv64 err:c0000033
[Kernel::onClickKernelMode] [ERR] InstallDriver D:\Temp\\OpenArkDrv64.sys err
```

是最新版本1.2.2

![image](https://user-images.githubusercontent.com/38303418/169024328-545a1bf7-7e71-4d72-9cdf-3a038ef78703.png)

**Comment by BlackINT3** [comment]
@shadowfish07 
是否被杀软拦截了，比如WinDefender？

**Comment by BlackINT3** [comment]
![image](https://user-images.githubusercontent.com/35478470/198052730-da8ba51d-e5e7-4b0f-9a99-436324d318dc.png)

通常情况是杀软拦截，close
