### ISSUE TITLE
win11 热键为空

### ISSUE THREAD

**Issue by jaxguo** [BlackINT3/OpenArk#89]
如图
管理员模式
进入内核均没用,点过刷新.
![QQ截图20220724003349](https://user-images.githubusercontent.com/9720390/180614267-728e2dec-7fe6-4978-a372-3f9cfb6f3070.png)

**Comment by DiXuanAoYi** [comment]
![image](https://user-images.githubusercontent.com/39654103/181001226-c728808c-b8df-40bc-968e-a89784a1d004.png)
我也遇到你的情况了，希望作者能解决下

**Comment by lsdt45** [comment]
同样的情况

**Comment by Nomango** [comment]
遇到一样的情况
![image](https://user-images.githubusercontent.com/22350366/186599819-fe99c04c-4df6-4c3f-a956-82c9b1eec0e1.png)

**Comment by shishirong** [comment]
我的连内核模式都无法进入
![image](https://user-images.githubusercontent.com/16620315/189509723-ed08b06d-b030-4f50-be15-d7d8c18bcf76.png)

**Comment by ExcuseLme** [comment]
![image](https://user-images.githubusercontent.com/43724060/192132180-27834075-98d0-4ac9-b513-f8845aadb553.png)
同样的问题, win11, 22H2版本, 进入内核模式后显示为空

**Comment by gbxm** [comment]
遇到了相同的情况

**Comment by LoveWaguan** [comment]
同样的问题，进入到内核模式，一样不显示热键

**Comment by joluzhu96** [comment]
![image](https://user-images.githubusercontent.com/39945725/197135697-9934b5ca-3334-43fa-a6c4-23c12546b97d.png)

![image](https://user-images.githubusercontent.com/39945725/197135754-edf4e5c8-b9d3-4c56-9eb1-158b55d273ac.png)
一样的问题

**Comment by sdegongzuo** [comment]
同样的情况
![image](https://user-images.githubusercontent.com/114134298/197925428-674b88e2-dc14-4f13-bb7c-eec4edce60b5.png)

**Comment by s192516** [comment]
+1 win10 22h2

**Comment by Aric-Sun** [comment]
+1
Windows 11 专业版 22H2 22621.900
```text
[UNONE::ObLoadDriverW] [ERR] NtLoadDriver service:\Registry\Machine\System\CurrentControlSet\Services\OpenArkDrv64 err:c0000603
[Kernel::onClickKernelMode] [ERR] InstallDriver C:\Users\TONYST~1\AppData\Local\Temp\OpenArkDrv64.sys err 
```

**Comment by BlackINT3** [comment]
v1.3.0 fixed, try it.
