### ISSUE TITLE
Cant Enter KernelMode

### ISSUE THREAD

**Issue by e04urmom** [BlackINT3/OpenArk#91]
There's no virus protect software either windows defender.
Install the drive manually?

[UNONE::ObLoadDriverW] [ERR] NtLoadDriver service:\Registry\Machine\System\CurrentControlSet\Services\OpenArkDrv64 err:c0000603
[Kernel::onClickKernelMode] [ERR] InstallDriver R:\USER_T~1\OpenArkDrv64.sys err

**Comment by BlackINT3** [comment]
@e04urmom give me your os version pls.

**Comment by e04urmom** [comment]
Windows 7 Pro build 7601 SP1.
Thanks you.

**Comment by everything411** [comment]
same problem on windows 11 dev 25197
```
[OpenArk::onActionCheckUpdate::::operator ()] [INFO] OpenArk is latest. 
[UNONE::ObLoadDriverW] [ERR] NtLoadDriver service:\Registry\Machine\System\CurrentControlSet\Services\OpenArkDrv64 err:c0000603
[Kernel::onClickKernelMode] [ERR] InstallDriver C:\Users\EVERYT~1\AppData\Local\Temp\OpenArkDrv64.sys err 
```

**Comment by just5325** [comment]
相同问题 win11正式版22H2
[UNONE::ObLoadDriverW] [ERR] NtLoadDriver service:\Registry\Machine\System\CurrentControlSet\Services\OpenArkDrv64 err:c0000603
[Kernel::onClickKernelMode] [ERR] InstallDriver C:\Users\ADMINI~1\AppData\Local\Temp\OpenArkDrv64.sys err

**Comment by zxyqq** [comment]
Windows 11 专业版 22H2
[UNONE::ObLoadDriverW] [ERR] NtLoadDriver service:\Registry\Machine\System\CurrentControlSet\Services\OpenArkDrv64 err:c0000603

**Comment by BlackINT3** [comment]
v1.3.0 fixed.
