### ISSUE TITLE
打开句柄（内存）列表的时候 

### ISSUE THREAD

**Issue by lousuo** [BlackINT3/OpenArk#96]
打开句柄（内存）列表的时候 会报错打开进程令牌失败？
内容：
         [ArkDrvApi::Process::OpenProcess] [ERR] OpenProcess pid:5374044 err:87
         [ArkDrvApi::Process::OpenProcess] [ERR] OpenProcess by Kernel pid:9148 err:2 （这个报错比较少见，但是也会出现）
使用win7 SP1和Inter CPU
使用时 关闭了所有杀软
另：希望杀进程能够更暴力一点？干不掉杀软 
谢谢

**Comment by lousuo** [comment]
有的时候结束进程后会直接未响应...然后白了 只能结束进程

**Comment by BlackINT3** [comment]
#104

**Comment by BlackINT3** [comment]
@lousuo 

v1.3.2 supported.  it can terminate anything.

BTW: You need enter kernel mode firstly.
